from __future__ import annotations

import gzip
import hashlib
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

from fastapi import Request
from fastapi.responses import Response

_ASSET_DIR = Path(__file__).with_name("static")
_SCHEMA_PATH = _ASSET_DIR / "openapi-public.json"
_GZIP_SCHEMA_PATH = _ASSET_DIR / "openapi-public.json.gz"


@dataclass(frozen=True)
class PublicOpenAPIPayload:
    body: bytes
    gzip_body: bytes
    etag: str
    gzip_etag: str


@lru_cache(maxsize=1)
def load_public_openapi_payload() -> PublicOpenAPIPayload:
    """Load pre-generated bytes; never construct route inventory at runtime."""

    body = _SCHEMA_PATH.read_bytes()
    gzip_body = _GZIP_SCHEMA_PATH.read_bytes()
    if gzip.decompress(gzip_body) != body:
        raise RuntimeError("public OpenAPI assets do not describe the same representation")
    return PublicOpenAPIPayload(
        body=body,
        gzip_body=gzip_body,
        etag=f'"{hashlib.sha256(body).hexdigest()}"',
        gzip_etag=f'"{hashlib.sha256(gzip_body).hexdigest()}"',
    )


def public_openapi_response(
    request: Request,
    payload: PublicOpenAPIPayload,
) -> Response:
    accepted: dict[str, float] = {}
    for item in request.headers.get("accept-encoding", "").split(","):
        token, *parameters = item.split(";")
        quality = 1.0
        for parameter in parameters:
            name, separator, value = parameter.strip().partition("=")
            if separator and name.lower() == "q":
                try:
                    quality = float(value)
                except ValueError:
                    quality = 0.0
                if not 0.0 <= quality <= 1.0:
                    quality = 0.0
        accepted[token.strip().lower()] = quality
    explicit = [accepted[coding] for coding in ("gzip", "x-gzip") if coding in accepted]
    gzip_quality = max(explicit) if explicit else accepted.get("*", 0.0)
    serve_gzip = gzip_quality > 0
    body = payload.gzip_body if serve_gzip else payload.body
    etag = payload.gzip_etag if serve_gzip else payload.etag
    headers = {
        "Cache-Control": "public, max-age=300, s-maxage=3600",
        "ETag": etag,
        "Vary": "Accept-Encoding",
    }
    if serve_gzip:
        headers["Content-Encoding"] = "gzip"
    elif "gzip" in request.headers.get("accept-encoding", ""):
        # Prevent outer GZipMiddleware from changing the representation after
        # its strong identity ETag has been selected.
        headers["Content-Encoding"] = "identity"
    validators = {
        token.strip().removeprefix("W/").strip()
        for token in request.headers.get("if-none-match", "").split(",")
    }
    if "*" in validators or etag in validators:
        return Response(status_code=304, headers=headers)
    return Response(content=body, media_type="application/json", headers=headers)
