"""Pydantic request models for the API surface.

Centralizing these here (instead of redefining at each route) keeps the
JSON wire shape near the type system, gives FastAPI autogenerated docs,
and makes the routes themselves much shorter — the validation rules
that used to live in `_helpers.py` extractors collapse into field-level
constraints.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, EmailStr, Field, field_validator, model_validator

from trusted_router.client_context import (
    ClientArch,
    ClientContextSource,
    ClientContextVersion,
    ClientLang,
    ClientOs,
    ClientPrevErrorClass,
    ClientPrevHost,
    ClientPrevOutcome,
    ClientSdk,
)
from trusted_router.money import (
    MAX_CHECKOUT_DOLLARS,
    MICRODOLLARS_PER_CENT,
    MICRODOLLARS_PER_DOLLAR,
    MIN_PAYPAL_CHECKOUT_MICRODOLLARS,
    dollars_to_microdollars,
)


class _Strict(BaseModel):
    """Reject unknown fields by default — keeps clients honest about schema."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)


class _Lenient(BaseModel):
    """Some legacy callers send extra OpenRouter-shaped fields; allow them."""

    model_config = ConfigDict(extra="allow", str_strip_whitespace=True)


class SignupRequest(_Strict):
    email: EmailStr
    name: str | None = Field(default=None, max_length=80)


class CreatorUsernameRequest(_Strict):
    username: str = Field(min_length=3, max_length=32)


class CheckoutRequest(_Lenient):
    amount: Decimal | str | int | float = Decimal("20")
    workspace_id: str | None = None
    purpose: Literal["identity_verification"] | None = None
    success_url: str | None = None
    cancel_url: str | None = None
    payment_method: Literal[
        "auto",
        "card",
        "ach",
        "bank",
        "us_bank_account",
        "stablecoin",
        "crypto",
        "usdc",
        "paypal",
        "adyen",
    ] = "auto"

    @field_validator("amount")
    @classmethod
    def amount_in_range(cls, value: Decimal | str | int | float) -> Decimal:
        microdollars = dollars_to_microdollars(value)
        if microdollars < MICRODOLLARS_PER_DOLLAR:
            raise ValueError("amount must be at least 1")
        if microdollars > MAX_CHECKOUT_DOLLARS * MICRODOLLARS_PER_DOLLAR:
            raise ValueError(f"amount must be at most {MAX_CHECKOUT_DOLLARS}")
        if microdollars % MICRODOLLARS_PER_CENT != 0:
            raise ValueError("amount must be exactly representable in cents")
        return Decimal(str(value))

    @model_validator(mode="after")
    def paypal_amount_in_range(self) -> CheckoutRequest:
        if (
            self.payment_method == "paypal"
            and dollars_to_microdollars(self.amount) < MIN_PAYPAL_CHECKOUT_MICRODOLLARS
        ):
            raise ValueError("PayPal checkout amount must be at least 10")
        return self


class X402FundingRequest(_Strict):
    amount: Decimal | str | int = Decimal("10.00")

    @field_validator("amount")
    @classmethod
    def amount_in_range(cls, value: Decimal | str | int) -> Decimal:
        microdollars = dollars_to_microdollars(value)
        if microdollars < MICRODOLLARS_PER_DOLLAR:
            raise ValueError("amount must be at least 1")
        if microdollars > MAX_CHECKOUT_DOLLARS * MICRODOLLARS_PER_DOLLAR:
            raise ValueError(f"amount must be at most {MAX_CHECKOUT_DOLLARS}")
        if microdollars % MICRODOLLARS_PER_CENT != 0:
            raise ValueError("amount must be exactly representable in cents")
        return Decimal(str(value))


class X402SettleRequest(_Strict):
    payment_intent_id: str = Field(pattern=r"^pi_[A-Za-z0-9_:-]{1,253}$")


def _validate_dollars(value: Decimal | str | int | float | None) -> Decimal | None:
    if value is None:
        return None
    try:
        decimal = Decimal(str(value))
    except Exception as exc:  # noqa: BLE001 - Decimal raises various errors.
        raise ValueError("must be a dollar amount") from exc
    if decimal < 0:
        raise ValueError("must be non-negative")
    return decimal


class CreateKeyRequest(_Lenient):
    name: str = Field(default="API key", max_length=120)
    limit: Decimal | None = None
    limit_reset: str | None = None
    # Optional per-window spend limits (USD; fixed UTC calendar windows).
    limit_daily: Decimal | None = None
    limit_weekly: Decimal | None = None
    limit_monthly: Decimal | None = None
    # False = hard-limit (429, default); True = alert by email without blocking.
    budget_alert_only: bool = False
    include_byok_in_limit: bool = True
    expires_at: str | None = None
    workspace_id: str | None = None
    management: bool = False
    tags: dict[str, Any] | None = None
    scopes: list[str] | None = None

    @field_validator("limit", "limit_daily", "limit_weekly", "limit_monthly", mode="before")
    @classmethod
    def _check_limit(cls, value: Any) -> Decimal | None:
        return _validate_dollars(value)


class PatchKeyRequest(_Lenient):
    name: str | None = Field(default=None, max_length=120)
    disabled: bool | None = None
    limit: Decimal | None = None
    limit_reset: str | None = None
    limit_daily: Decimal | None = None
    limit_weekly: Decimal | None = None
    limit_monthly: Decimal | None = None
    budget_alert_only: bool | None = None
    include_byok_in_limit: bool | None = None
    tags: dict[str, Any] | None = None

    @field_validator("limit", "limit_daily", "limit_weekly", "limit_monthly", mode="before")
    @classmethod
    def _check_limit(cls, value: Any) -> Decimal | None:
        return _validate_dollars(value)


class UpsertByokRequest(_Strict):
    api_key: str | None = None
    key: str | None = None
    secret_ref: str | None = None
    key_hint: str | None = Field(default=None, max_length=80)


class BroadcastDestinationCreateRequest(_Strict):
    type: str = Field(min_length=1, max_length=32)
    name: str = Field(default="Broadcast destination", min_length=1, max_length=120)
    endpoint: str | None = None
    enabled: bool = True
    include_content: bool = False
    method: Literal["POST", "PUT"] = "POST"
    headers: dict[str, str] | None = None
    api_key: str | None = None

    @field_validator("type")
    @classmethod
    def normalize_type(cls, value: str) -> str:
        return value.strip().lower()


class BroadcastDestinationPatchRequest(_Strict):
    name: str | None = Field(default=None, min_length=1, max_length=120)
    endpoint: str | None = None
    enabled: bool | None = None
    include_content: bool | None = None
    method: Literal["POST", "PUT"] | None = None
    headers: dict[str, str] | None = None
    api_key: str | None = None


class CustomModelCreateRequest(_Strict):
    name: str = Field(min_length=1, max_length=120)
    slug: str | None = Field(default=None, min_length=3, max_length=96)
    base_model_id: str = Field(min_length=1, max_length=256)
    hidden_prompt: str = Field(min_length=0, max_length=262_144)
    markup_basis_points: int = Field(default=0, ge=0, le=30_000)
    enabled: bool = True


class CustomModelPatchRequest(_Strict):
    name: str | None = Field(default=None, min_length=1, max_length=120)
    slug: str | None = Field(default=None, min_length=3, max_length=96)
    base_model_id: str | None = Field(default=None, min_length=1, max_length=256)
    hidden_prompt: str | None = Field(default=None, min_length=0, max_length=262_144)
    markup_basis_points: int | None = Field(default=None, ge=0, le=30_000)
    enabled: bool | None = None


class UserModelCreateRequest(_Strict):
    name: str = Field(min_length=1, max_length=120)
    slug: str | None = Field(default=None, min_length=3, max_length=96)
    kind: Literal["machine", "agent", "human"]
    description: str = Field(default="", max_length=2000)
    display_identity: Literal["handle", "verified_name"] = "handle"
    display_name: str = Field(min_length=1, max_length=120)
    endpoint_url: str = Field(min_length=1, max_length=2048)
    upstream_model_id: str | None = Field(default=None, min_length=1, max_length=256)
    endpoint_api_key: str | None = Field(default=None, min_length=1, max_length=8192)
    supports_streaming: bool = True
    heartbeat_interval_seconds: int | None = Field(default=None, ge=5, le=3600)
    max_concurrency: int = Field(default=4, ge=1, le=100)
    prompt_price_microdollars_per_million_tokens: int = Field(default=0, ge=0)
    completion_price_microdollars_per_million_tokens: int = Field(default=0, ge=0)


class UserModelPatchRequest(_Strict):
    name: str | None = Field(default=None, min_length=1, max_length=120)
    slug: str | None = Field(default=None, min_length=3, max_length=96)
    kind: Literal["machine", "agent", "human"] | None = None
    description: str | None = Field(default=None, max_length=2000)
    display_identity: Literal["handle", "verified_name"] | None = None
    display_name: str | None = Field(default=None, min_length=1, max_length=120)
    endpoint_url: str | None = Field(default=None, min_length=1, max_length=2048)
    upstream_model_id: str | None = Field(default=None, min_length=1, max_length=256)
    endpoint_api_key: str | None = Field(default=None, min_length=1, max_length=8192)
    supports_streaming: bool | None = None
    heartbeat_interval_seconds: int | None = Field(default=None, ge=5, le=3600)
    max_concurrency: int | None = Field(default=None, ge=1, le=100)
    prompt_price_microdollars_per_million_tokens: int | None = Field(default=None, ge=0)
    completion_price_microdollars_per_million_tokens: int | None = Field(default=None, ge=0)


class EarningsTransferRequest(_Strict):
    workspace_id: str = Field(min_length=1, max_length=80)
    amount_microdollars: int
    idempotency_key: str | None = Field(default=None, min_length=1, max_length=64)


class SpendLeaseEcho(_Strict):
    lease_id: str | None = Field(default=None, max_length=64)
    state: str = Field(min_length=1, max_length=64)
    remaining_micro: int | None = Field(default=None, ge=0)
    enclave_estimate_micro: int | None = Field(default=None, ge=0)
    catalog_version: str | None = Field(default=None, max_length=128)
    would_admit: bool | None = None


class SpendLeaseBootRegistrationRequest(_Strict):
    kid: str = Field(min_length=1, max_length=128)
    receipt_public_key: dict[str, Any]
    attestation_evidence: str = Field(min_length=1, max_length=2 * 1024 * 1024)
    attestation_kind: str = Field(min_length=1, max_length=64)


class SpendLeaseAdmissionMarker(_Strict):
    accepted: Literal[True]
    receipt_hash: str = Field(pattern="^[0-9a-f]{64}$")


class SpendLeaseAdmissionRejectedError(_Strict):
    code: Literal[409]
    message: Literal["Spend-lease admission was rejected"]
    type: Literal["admission_rejected"]
    source: Literal["router"]
    reason: Literal[
        "receipt_invalid",
        "boot_not_accepted",
        "boot_mismatch",
        "lease_not_open",
        "window",
        "policy_mismatch",
        "estimate_mismatch",
        "capacity",
        "hold_refused",
        "scope_conflict",
        "reuse_lost",
        "not_accepting",
    ]


class SpendLeaseAdmissionRejected(_Strict):
    error: SpendLeaseAdmissionRejectedError


class GatewayAuthorizeRequest(_Lenient):
    api_key_hash: str | None = Field(default=None, min_length=1)
    api_key_lookup_hash: str | None = Field(default=None, min_length=1)
    idempotency_key: str | None = Field(default=None, min_length=1, max_length=256)
    request_fingerprint: str | None = Field(default=None, pattern="^[0-9a-f]{64}$")
    model: str = Field(min_length=1)
    models: list[str] | None = None
    provider: dict[str, Any] | None = None
    requested_parameters: list[str] | None = None
    estimated_input_tokens: int = Field(default=1, ge=0)
    max_output_tokens: int | None = Field(default=None, ge=1)
    max_completion_tokens: int | None = Field(default=None, ge=1)
    max_tokens: int | None = Field(default=None, ge=1)
    service_tier: str | None = Field(default=None, min_length=1, max_length=20)
    stream: bool | None = None
    region: str | None = None
    user: str | None = Field(default=None, max_length=256)
    session_id: str | None = Field(default=None, max_length=256)
    trace: dict[str, Any] | None = None
    metadata: dict[str, Any] | None = None
    tags: dict[str, Any] | None = None
    app: str | None = Field(default=None, max_length=120)
    http_referer: str | None = Field(default=None, max_length=2048)
    app_categories: list[str] | None = None
    # Route-failover visibility from the attested gateway: pre-output provider
    # attempts that failed before the winning candidate answered, as
    # "provider|endpoint|error_class" strings (metadata only, no content).
    route_fallbacks: int | None = Field(default=None, ge=0)
    route_failures: list[str] | None = None
    route_type: str | None = None
    # Set only by the attested gateway after validating x-inference-receipt.
    # The control plane freezes the resulting total fee on the authorization.
    inference_receipt: bool = False
    # Attested hosted tools may reserve a bounded non-token cost on the same
    # atomic hold as their planner model call. This is internal-only and is
    # accepted only for enclave-owned hosted tools and asynchronous media.
    additional_cost_reservation_microdollars: int = Field(default=0, ge=0, le=100_000_000)
    spend_lease_echo: SpendLeaseEcho | None = None
    # Compact JWS signed by the admitted lease's attested boot. It is excluded
    # from the logical request fingerprint and is consequential only in Stage C.
    spend_lease_admission: str | None = Field(default=None, min_length=1, max_length=16_384)
    invocation_nonce: str | None = Field(default=None, max_length=64)

    @model_validator(mode="after")
    def key_identifier_required(self) -> GatewayAuthorizeRequest:
        if not self.api_key_hash and not self.api_key_lookup_hash:
            raise ValueError("api_key_hash or api_key_lookup_hash is required")
        return self

    @property
    def output_estimate(self) -> int:
        if self.max_tokens is not None:
            return self.max_tokens
        if self.max_completion_tokens is not None:
            return self.max_completion_tokens
        if self.max_output_tokens is not None:
            return self.max_output_tokens
        return 512


class GatewayFetchImageRequest(_Lenient):
    # Some gateway paths proxy image URL fetches through the control plane.
    # The control plane resolves DNS, rejects private/loopback IPs, and
    # returns the bytes as base64 to be re-embedded inline by the gateway.
    url: str = Field(min_length=1)


class GatewayVideoJobPrepareRequest(_Strict):
    job_id: str = Field(min_length=8, max_length=128)
    authorization_id: str = Field(min_length=1, max_length=128)
    model: str = Field(min_length=1, max_length=256)
    provider: str = Field(min_length=1, max_length=64)
    endpoint_id: str = Field(min_length=1, max_length=512)
    provider_model: str = Field(min_length=1, max_length=256)
    quoted_microdollars: int = Field(ge=1, le=100_000_000)
    input_mode: str = Field(default="text", pattern="^(text|image|reference|video)$")
    duration_seconds: int = Field(default=0, ge=0, le=60)
    resolution: str = Field(default="", max_length=32)
    aspect_ratio: str = Field(default="", max_length=32)
    generate_audio: bool = False
    region: str = Field(default="", max_length=64)


class GatewayVideoJobQueuedRequest(_Strict):
    provider_job_id: str = Field(min_length=1, max_length=512)
    # Optional during the rolling gateway upgrade. Older gateways queued the
    # route prepared on the job; newer gateways send the actual fallback route.
    provider: str | None = Field(default=None, min_length=1, max_length=64)
    endpoint_id: str | None = Field(default=None, min_length=1, max_length=512)
    provider_model: str | None = Field(default=None, min_length=1, max_length=256)
    quoted_microdollars: int | None = Field(default=None, ge=1, le=100_000_000)
    poll_after_seconds: int = Field(default=5, ge=1, le=300)


class GatewayVideoJobLookupRequest(_Strict):
    api_key_lookup_hash: str = Field(min_length=1, max_length=128)


class GatewayVideoJobClaimRequest(_Strict):
    lease_owner: str = Field(min_length=1, max_length=128)
    limit: int = Field(default=10, ge=1, le=100)
    lease_seconds: int = Field(default=60, ge=10, le=600)


class GatewayVideoJobUpdateRequest(_Strict):
    status: str = Field(pattern="^(pending|in_progress|completed|failed)$")
    lease_owner: str | None = Field(default=None, max_length=128)
    provider_status: str | None = Field(default=None, max_length=64)
    generation_id: str | None = Field(default=None, max_length=128)
    error: str | None = Field(default=None, max_length=500)
    poll_after_seconds: int = Field(default=5, ge=1, le=300)


class GatewayValidateRequest(_Lenient):
    api_key_hash: str | None = Field(default=None, min_length=1)
    api_key_lookup_hash: str | None = Field(default=None, min_length=1)
    route_type: str | None = None

    @model_validator(mode="after")
    def key_identifier_required(self) -> GatewayValidateRequest:
        if not self.api_key_hash and not self.api_key_lookup_hash:
            raise ValueError("api_key_hash or api_key_lookup_hash is required")
        return self


class GatewayResolveCustomModelRequest(_Lenient):
    api_key_hash: str | None = Field(default=None, min_length=1)
    api_key_lookup_hash: str | None = Field(default=None, min_length=1)
    model: str = Field(min_length=1, max_length=256)
    route_type: str | None = None

    @model_validator(mode="after")
    def key_identifier_required(self) -> GatewayResolveCustomModelRequest:
        if not self.api_key_hash and not self.api_key_lookup_hash:
            raise ValueError("api_key_hash or api_key_lookup_hash is required")
        return self


class ReconcileGenerationActivityRequest(_Strict):
    workspace_id: str = Field(min_length=1)
    date: str | None = None
    limit: int = Field(default=1000, ge=1, le=10_000)


class GatewayClientContext(_Strict):
    v: ClientContextVersion | None = None
    source: ClientContextSource | None = None
    sdk: ClientSdk | None = None
    sdk_version: str | None = Field(
        default=None,
        pattern=r"^[0-9]{1,4}\.[0-9]{1,4}\.[0-9]{1,4}([-+][0-9A-Za-z.]{0,20})?$",
        max_length=32,
    )
    lang: ClientLang | None = None
    runtime: str | None = Field(default=None, pattern=r"^[a-z]{1,10}/[0-9A-Za-z.+-]{1,24}$")
    os: ClientOs | None = None
    arch: ClientArch | None = None
    timeout_ms: int | None = Field(default=None, ge=1, le=3_600_000)
    attempt: int | None = Field(default=None, ge=0, le=99)
    prev_outcome: ClientPrevOutcome | None = None
    prev_error_class: ClientPrevErrorClass | None = None
    prev_host: ClientPrevHost | None = None
    prev_elapsed_ms: int | None = Field(default=None, ge=0, le=3_600_000)
    since_first_ms: int | None = Field(default=None, ge=0, le=3_600_000)
    stream: bool | None = None
    failover_used: bool | None = None


class GatewaySettleRequest(_Lenient):
    authorization_id: str = Field(min_length=1)
    actual_input_tokens: int | None = Field(default=None, ge=0)
    actual_output_tokens: int | None = Field(default=None, ge=0)
    input_tokens: int | None = Field(default=None, ge=0)
    output_tokens: int | None = Field(default=None, ge=0)
    # Prompt-cache accounting reported by the attested gateway. NOTE the
    # provider-dependent semantics the settle handler normalizes:
    # Anthropic's input_tokens EXCLUDE cached tokens; OpenAI-compatible
    # and Gemini prompt counts INCLUDE the cached subset.
    cache_read_input_tokens: int | None = Field(default=None, ge=0)
    cache_creation_input_tokens: int | None = Field(default=None, ge=0)
    # Provider-reported initial context used only to choose a context-priced
    # tier. actual_input_tokens remains the complete billable input count.
    price_tier_input_tokens: int | None = Field(default=None, ge=0)
    reasoning_tokens: int | None = Field(default=None, ge=0)
    service_tier: str | None = Field(default=None, min_length=1, max_length=20)
    request_id: str | None = None
    finish_reason: str | None = None
    status: str | None = None
    streamed: bool = False
    usage_estimated: bool = False
    elapsed_seconds: float | None = Field(default=None, gt=0)
    first_token_seconds: float | None = Field(default=None, gt=0)
    error_status: int | None = Field(default=None, ge=100, le=599)
    error_type: str | None = Field(default=None, max_length=80)
    app: str | None = None
    model: str | None = None
    selected_model: str | None = None
    endpoint: str | None = None
    selected_endpoint: str | None = None
    user: str | None = Field(default=None, max_length=256)
    session_id: str | None = Field(default=None, max_length=256)
    trace: dict[str, Any] | None = None
    metadata: dict[str, Any] | None = None
    tags: dict[str, Any] | None = None
    http_referer: str | None = Field(default=None, max_length=2048)
    app_categories: list[str] | None = None
    route_type: str | None = None
    client: dict[str, Any] | None = None
    gateway_request_id: str | None = Field(default=None, max_length=64)
    additional_cost_microdollars: int = Field(default=0, ge=0, le=100_000_000)
    video_input_mode: str | None = Field(default=None, pattern="^(text|image|reference|video)$")
    video_duration_seconds: int | None = Field(default=None, ge=0, le=60)
    video_resolution: str | None = Field(default=None, max_length=32)
    video_aspect_ratio: str | None = Field(default=None, max_length=32)
    video_generate_audio: bool | None = None

    @property
    def input_count(self) -> int:
        if self.actual_input_tokens is not None:
            return self.actual_input_tokens
        return self.input_tokens or 0

    @property
    def output_count(self) -> int:
        if self.actual_output_tokens is not None:
            return self.actual_output_tokens
        return self.output_tokens or 0

    @property
    def cache_read_count(self) -> int:
        return self.cache_read_input_tokens or 0

    @property
    def cache_creation_count(self) -> int:
        return self.cache_creation_input_tokens or 0

    @property
    def selected_model_id(self) -> str | None:
        return self.selected_model or self.model

    @property
    def selected_endpoint_id(self) -> str | None:
        return self.selected_endpoint or self.endpoint


class GatewayHeartbeatUsage(_Strict):
    actual_input_tokens: int | None = Field(default=None, ge=0)
    actual_output_tokens: int | None = Field(default=None, ge=0)
    input_tokens: int | None = Field(default=None, ge=0)
    output_tokens: int | None = Field(default=None, ge=0)
    cache_read_input_tokens: int | None = Field(default=None, ge=0)
    cache_creation_input_tokens: int | None = Field(default=None, ge=0)
    price_tier_input_tokens: int | None = Field(default=None, ge=0)
    reasoning_tokens: int | None = Field(default=None, ge=0)

    @property
    def input_count(self) -> int:
        if self.actual_input_tokens is not None:
            return self.actual_input_tokens
        return self.input_tokens or 0

    @property
    def output_count(self) -> int:
        if self.actual_output_tokens is not None:
            return self.actual_output_tokens
        return self.output_tokens or 0

    def canonical_counts(self) -> dict[str, int]:
        return {
            "input_tokens": self.input_count,
            "output_tokens": self.output_count,
            "cache_read_input_tokens": self.cache_read_input_tokens or 0,
            "cache_creation_input_tokens": self.cache_creation_input_tokens or 0,
            "price_tier_input_tokens": self.price_tier_input_tokens or 0,
            "reasoning_tokens": self.reasoning_tokens or 0,
        }


class GatewayHeartbeatRequest(_Strict):
    authorization_id: str = Field(min_length=1, max_length=128)
    seq: int = Field(ge=1)
    started_at_ms: int = Field(ge=0)
    selected_endpoint_id: str = Field(min_length=1, max_length=128)
    usage: GatewayHeartbeatUsage
    elapsed_ms: int = Field(ge=0)
    stream: bool


def model_to_dict(model: BaseModel) -> dict[str, Any]:
    """Pydantic v2 `.model_dump(exclude_none=True)` shorthand."""
    return model.model_dump(exclude_none=True)
