"""Pydantic request models for the API surface.

Centralizing these here (instead of redefining at each route) keeps the
JSON wire shape near the type system, gives FastAPI autogenerated docs,
and makes the routes themselves much shorter — the validation rules
that used to live in `_helpers.py` extractors collapse into field-level
constraints.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, EmailStr, Field, field_validator, model_validator

from trusted_router.money import (
    MAX_CHECKOUT_DOLLARS,
    MICRODOLLARS_PER_DOLLAR,
    dollars_to_microdollars,
)


class _Strict(BaseModel):
    """Reject unknown fields by default — keeps clients honest about schema."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)


class _Lenient(BaseModel):
    """Some legacy callers send extra OpenRouter-shaped fields; allow them."""

    model_config = ConfigDict(extra="allow", str_strip_whitespace=True)


class SignupRequest(_Strict):
    email: EmailStr
    name: str | None = Field(default=None, max_length=80)


class CheckoutRequest(_Lenient):
    amount: Decimal | str | int | float = Decimal("20")
    workspace_id: str | None = None
    success_url: str | None = None
    cancel_url: str | None = None
    payment_method: Literal["auto", "stablecoin", "crypto", "usdc"] = "auto"

    @field_validator("amount")
    @classmethod
    def amount_in_range(cls, value: Decimal | str | int | float) -> Decimal:
        microdollars = dollars_to_microdollars(value)
        if microdollars < MICRODOLLARS_PER_DOLLAR:
            raise ValueError("amount must be at least 1")
        if microdollars > MAX_CHECKOUT_DOLLARS * MICRODOLLARS_PER_DOLLAR:
            raise ValueError(f"amount must be at most {MAX_CHECKOUT_DOLLARS}")
        return Decimal(str(value))


def _validate_dollars(value: Decimal | str | int | float | None) -> Decimal | None:
    if value is None:
        return None
    try:
        decimal = Decimal(str(value))
    except Exception as exc:  # noqa: BLE001 - Decimal raises various errors.
        raise ValueError("must be a dollar amount") from exc
    if decimal < 0:
        raise ValueError("must be non-negative")
    return decimal


class CreateKeyRequest(_Lenient):
    name: str = Field(default="API key", max_length=120)
    limit: Decimal | None = None
    limit_reset: str | None = None
    include_byok_in_limit: bool = True
    expires_at: str | None = None
    workspace_id: str | None = None
    management: bool = False

    @field_validator("limit", mode="before")
    @classmethod
    def _check_limit(cls, value: Any) -> Decimal | None:
        return _validate_dollars(value)


class PatchKeyRequest(_Lenient):
    name: str | None = Field(default=None, max_length=120)
    disabled: bool | None = None
    limit: Decimal | None = None
    limit_reset: str | None = None
    include_byok_in_limit: bool | None = None

    @field_validator("limit", mode="before")
    @classmethod
    def _check_limit(cls, value: Any) -> Decimal | None:
        return _validate_dollars(value)


class UpsertByokRequest(_Strict):
    api_key: str | None = None
    key: str | None = None
    secret_ref: str | None = None
    key_hint: str | None = Field(default=None, max_length=80)


class GatewayAuthorizeRequest(_Lenient):
    api_key_hash: str | None = Field(default=None, min_length=1)
    api_key_lookup_hash: str | None = Field(default=None, min_length=1)
    model: str = Field(min_length=1)
    models: list[str] | None = None
    provider: dict[str, Any] | None = None
    estimated_input_tokens: int = Field(default=1, ge=0)
    max_output_tokens: int | None = Field(default=None, ge=1)
    max_tokens: int | None = Field(default=None, ge=1)
    region: str | None = None

    @model_validator(mode="after")
    def key_identifier_required(self) -> GatewayAuthorizeRequest:
        if not self.api_key_hash and not self.api_key_lookup_hash:
            raise ValueError("api_key_hash or api_key_lookup_hash is required")
        return self

    @property
    def output_estimate(self) -> int:
        if self.max_output_tokens is not None:
            return self.max_output_tokens
        if self.max_tokens is not None:
            return self.max_tokens
        return 512


class GatewaySettleRequest(_Lenient):
    authorization_id: str = Field(min_length=1)
    actual_input_tokens: int | None = Field(default=None, ge=0)
    actual_output_tokens: int | None = Field(default=None, ge=0)
    input_tokens: int | None = Field(default=None, ge=0)
    output_tokens: int | None = Field(default=None, ge=0)
    request_id: str | None = None
    finish_reason: str | None = None
    status: str | None = None
    streamed: bool = False
    usage_estimated: bool = False
    elapsed_seconds: float | None = Field(default=None, gt=0)
    first_token_seconds: float | None = Field(default=None, gt=0)
    error_status: int | None = Field(default=None, ge=100, le=599)
    error_type: str | None = Field(default=None, max_length=80)
    app: str | None = None
    model: str | None = None
    selected_model: str | None = None
    endpoint: str | None = None
    selected_endpoint: str | None = None

    @property
    def input_count(self) -> int:
        if self.actual_input_tokens is not None:
            return self.actual_input_tokens
        return self.input_tokens or 0

    @property
    def output_count(self) -> int:
        if self.actual_output_tokens is not None:
            return self.actual_output_tokens
        return self.output_tokens or 0

    @property
    def selected_model_id(self) -> str | None:
        return self.selected_model or self.model

    @property
    def selected_endpoint_id(self) -> str | None:
        return self.selected_endpoint or self.endpoint


def model_to_dict(model: BaseModel) -> dict[str, Any]:
    """Pydantic v2 `.model_dump(exclude_none=True)` shorthand."""
    return model.model_dump(exclude_none=True)
