"""The pull-request check that turns the BYOK envelope ordering constraint into CI.

THE LAW
-------
A control plane may run only a build whose set of WRITTEN BYOK envelope formats
is a subset of the formats accepted by EVERY enclave serving that cloud, in
every region, and the check must refuse whenever it cannot establish that subset
relation — not only when it can disprove it.

WHY THIS IS A PROOF AND NOT A TEST
----------------------------------
The thing under test is a refusal. Its value is entirely in the cases where it
says no, and a refusal that never fires is indistinguishable from no check at
all while looking exactly like a check in CI. So the assertions here are almost
all negative: fabricate the outage, fabricate the missing provenance, fabricate
the region nobody wrote down, and require a non-zero verdict for each. The happy
path is one test out of many, and it is the least interesting one.

The subset relation also has to be DERIVED on both sides, and that is asserted
too. A check that hardcodes "writes V2, needs V2" is correct until the day a V3
write lands, at which point it keeps passing while asserting a fact about a
format the build no longer writes.

BOTH SIDES OF THAT DERIVATION WERE DEFEATED, THE WRITE SIDE TWICE
------------------------------------------------------------------
Adversarial review broke both halves, and the tests it produced are kept here as
the ones that matter most:

* ACCEPTS came from parsing case labels out of the switch in `envelopeAAD`.
  Four compiling, gofmt-clean edits kept `case AlgorithmV2:` in cache.go while
  rejecting v2 at run time — an erroring case body, a kill switch ahead of the
  switch, a rejection in the caller, a renamed live dispatch with the old
  function left as dead code — and all four passed with exit 0. The check now
  reads a declaration the enclave repo GENERATES from a round trip through
  (*Cache).Resolve, and binds it to that commit's package by sha256.
  `test_a_case_label_is_not_acceptance` and
  `test_a_declaration_that_no_longer_matches_the_package_blocks` are that fix.
* WRITES came from calls spelled `EncryptedSecretEnvelope` in one hardcoded
  file. An alias, a subclass, dataclasses.replace, an assignment to
  `.algorithm`, and a write site in any other module were all invisible. The
  fix was a wider scan, and a SECOND review walked past that one too — an
  annotated alias, an alias imported from a sibling module, a subclass defined
  in a sibling module — because the answer was still syntax.
  `test_written_formats_sees_a_v3_written_through_an_indirection` carries every
  shape from both rounds.
* So the write side is no longer primarily syntax. `probe_write_entry_points()`
  CALLS this tree and reads `.algorithm` off the envelopes those calls produced,
  and the check uses the union of that and the scan. The tests for it are
  `test_the_probe_reports_the_format_a_real_call_produced`,
  `test_the_probe_refuses_when_its_recorder_is_blind`, and
  `test_an_entry_point_with_no_probe_is_a_refusal` — the last being the
  enumeration closure that keeps the probe's coverage checkable rather than
  claimed.

TWO PATHS, AND THE CONSTANT THAT ROUTES BETWEEN THEM
-----------------------------------------------------
The check runs on every pull request (.github/workflows/ci.yml), so it must be
silent on the pull requests that do not touch envelope formats — and the loud
path CANNOT pass for any cloud today. Read live on 2026-08-16: AWS and Azure
publish `"source_commit": "not-configured"`, and GCP's `f57b791` carries no
`accepted_formats.json` (that file is generated by quill-cloud-proxy#177, which
is not merged). `main()` therefore routes on one comparison: the derived written
set against `BASELINE_WRITTEN_FORMATS`.

That constant is hand-maintained, which is the defect class this repository
keeps being bitten by, so it is pinned rather than believed:
`test_the_baseline_matches_what_this_tree_writes` runs the real derivation
against the real tree and asserts equality. Without it the check is silent
whenever the constant is stale, which is the same as not running. The other two
directions are `test_an_unchanged_write_side_is_silent_and_reads_no_network`,
which drives the real `main()` with EVERY network seam replaced by a function
that raises, and `test_a_new_written_format_takes_the_loud_path_and_blocks`.

WHAT NO TEST HERE COVERS ABOUT THE ROUTING
-------------------------------------------
A change that alters the written set and updates BASELINE_WRITTEN_FORMATS in the
same commit is silent from the NEXT commit onwards. What makes that safe is that
the two edits are one diff, arriving together in front of a reviewer, and that
the loud path has already run on the commit that made them differ. Nothing here
enforces that a human read that diff.

SCOPE LIMIT, stated plainly
---------------------------
* Nothing here touches the network, so nothing here proves the live attestation
  endpoints answer, that the published records are reachable, or that
  raw.githubusercontent.com serves a file at an arbitrary commit. Those are
  the check's real failure modes in production and they are covered only by it
  failing closed on any exception, which IS asserted, on fabricated exceptions.
* No signature is verified here or by the code under test. The attestation
  fixtures below are unsigned, and the check would accept them in production
  too; it reads attestations through scripts/verify_trust_measurements.py's own
  samplers, which do not verify signatures either.
* `source_commit` is an assertion by whoever ran the enclave release, not a
  measurement. These tests prove the check refuses when it is absent. They
  cannot prove — and neither can the check — that a present one is the commit
  that built the running enclave.
* The accepted-formats declaration is proved here to be bound to the package
  source at the same commit, for every non-test .go file that commit's package
  contains. It is NOT proved to have been generated rather than hand-written;
  that is quill-cloud-proxy's CI running the generating test, and the property
  that the generator measures behaviour is proved there, in
  enclave-go/internal/byokcache/accepted_formats_test.go, not here. Nor does
  anything here or there show that the round trip the declaration records would
  still succeed under the enclave's own run-time configuration: a v2 refusal
  behind an environment variable produces a green CI and a V1,V2 declaration.
* The behavioural write probe is exercised here against the REAL modules, so
  these tests do depend on this tree importing and on a local AES key wrapper
  working. They do not prove that every write path is probed — that is the
  enumeration closure, which is itself only as complete as the return
  annotations in src/trusted_router.
* The subset check is over algorithm STRINGS. It does not prove the two
  implementations of a shared format agree byte for byte; that is
  tests/test_byok_aad_namespace_property.py's pinned hex vector, and the two
  proofs are independent.
* Region coverage: the check refuses when the record accepts a measurement this
  run never observed, and `test_an_accepted_measurement_no_region_served
  _blocks` fabricates exactly the shape the live Azure mirror had. What no test
  and no check can see is an enclave serving a cloud while appearing in neither
  the record's `regions` array nor its accepted set.
* Nothing here, and nothing in the code under test, stops a DEPLOY. The check
  is a CI job; deploy.yml and both hand-run cloud scripts do not call it.
"""

from __future__ import annotations

import base64
import hashlib
import json
from typing import Any

import cbor2
import pytest

import scripts.check_format_ordering as gate
from scripts.check_format_ordering import (
    BASELINE_WRITTEN_FORMATS,
    DECLARATION_PATH,
    DECLARATION_SCHEMA,
    ENCLAVE_PACKAGE,
    PLANES,
    PROBE_CONTROL_FORMAT,
    RegionResult,
    WriteProbe,
    accepted_formats,
    check_plane,
    derive_written_formats,
    gather,
    probe_write_entry_points,
    read_write_surface,
    regions_of,
    render,
    scan_write_surface,
    written_formats,
)
from scripts.verify_trust_measurements import Fetched, Transport

V1 = "TR-BYOK-ENVELOPE-AES-256-GCM-V1"
V2 = "TR-BYOK-ENVELOPE-AES-256-GCM-V2"
V3 = "TR-BYOK-ENVELOPE-AES-256-GCM-V3"
CONTROL = "TR-BYOK-ENVELOPE-AES-256-GCM-PROBE-NOT-A-FORMAT"

COMMIT_V1_ONLY = "1111111"
COMMIT_V1_AND_V2 = "2222222"

GCP_DIGEST = "sha256:" + "fa" * 32
AWS_PCR0 = "23" * 48
AZURE_UAEN = "c5" * 32
AZURE_SEA = "f3" * 32

UAEN_ISSUER = "https://trquilluaen.uaen.attest.azure.net"
SEA_ISSUER = "https://trquillsea.sasia.attest.azure.net"
UAEN_URL = "https://api-azure.trustedrouter.com/attestation"
SEA_URL = "https://api-azure-sea.trustedrouter.com/attestation"


# --------------------------------------------------------------------------
# Fixtures fabricated to the shape of the real thing
# --------------------------------------------------------------------------


def _jwt(claims: dict[str, Any]) -> bytes:
    """An unsigned JWT. The check reads claims and never checks signatures."""
    encode = lambda raw: base64.urlsafe_b64encode(raw).rstrip(b"=")  # noqa: E731
    return b".".join(
        (
            encode(json.dumps({"alg": "none"}).encode()),
            encode(json.dumps(claims).encode()),
            b"",
        )
    )


def gcp_attestation(digest: str = GCP_DIGEST) -> bytes:
    return _jwt(
        {
            "iss": "https://confidentialcomputing.googleapis.com",
            "aud": "quill-cloud",
            "submods": {"container": {"image_digest": digest}},
        }
    )


def azure_attestation(hostdata: str, issuer: str) -> bytes:
    return _jwt(
        {
            "iss": issuer,
            "x-ms-attestation-type": "sevsnpvm",
            "x-ms-sevsnpvm-hostdata": hostdata,
        }
    )


def aws_attestation(pcr0: str = AWS_PCR0) -> bytes:
    """A 4-element COSE_Sign1 envelope carrying a Nitro attestation document.

    Unsigned: the protected header and signature are empty, because the check
    parses the payload and never verifies the chain.
    """
    document = cbor2.dumps(
        {"digest": "SHA384", "pcrs": {0: bytes.fromhex(pcr0)}, "module_id": "i-0-enc0"}
    )
    return bytes(cbor2.dumps([b"", {}, document, b""]))


def cache_go(*, accepts_v2: bool) -> bytes:
    """cache.go as the enclave really shapes it.

    Present in these fixtures so the `case AlgorithmV2:` label can be varied
    INDEPENDENTLY of the declaration. The label is what the old parser read; the
    tests below require that varying it changes nothing on its own, and that
    changing the file at all invalidates a declaration generated from the
    previous one.
    """
    case_v2 = "\tcase AlgorithmV2:\n\t\treturn aadV2(namespaceProvider, workspaceID, provider)\n"
    return (
        "package byokcache\n\n"
        "const (\n"
        f'\tAlgorithm = "{V1}"\n'
        f'\tAlgorithmV2 = "{V2}"\n'
        '\tnamespaceProvider = "provider"\n'
        ")\n\n"
        "func envelopeAAD(algorithm, workspaceID, provider string) ([]byte, error) {\n"
        "\tswitch algorithm {\n"
        "\tcase Algorithm:\n"
        "\t\treturn aad(workspaceID, provider), nil\n"
        f"{case_v2 if accepts_v2 else ''}"
        "\tdefault:\n"
        '\t\treturn nil, fmt.Errorf("byokcache: unsupported envelope algorithm %q", algorithm)\n'
        "\t}\n"
        "}\n"
    ).encode()


def declaration(
    accepted: list[str], sources: dict[str, bytes], overrides: dict[str, Any] | None = None
) -> bytes:
    """The generated declaration, in the shape the Go test writes it."""
    record: dict[str, Any] = {
        "schema": DECLARATION_SCHEMA,
        "package": ENCLAVE_PACKAGE,
        "accepted": accepted,
        "rejected_control": CONTROL,
        "probe": "seal an envelope, then require (*Cache).Resolve to return the plaintext",
        "generator": "go test ./internal/byokcache -run TestAcceptedFormatsDeclaration",
        "source_sha256": {name: hashlib.sha256(body).hexdigest() for name, body in sources.items()},
    }
    record.update(overrides or {})
    return json.dumps(record, indent=2).encode()


def enclave_tree(accepted: list[str], *, accepts_v2_label: bool | None = None) -> dict[str, bytes]:
    """One commit's worth of the enclave package: the sources and the declaration.

    `accepts_v2_label` controls only the case label in cache.go and defaults to
    agreeing with the declaration. The check must not read it either way.
    """
    label = accepts_v2_label if accepts_v2_label is not None else (V2 in accepted)
    sources = {"cache.go": cache_go(accepts_v2=label)}
    files = {f"{ENCLAVE_PACKAGE}/{name}": body for name, body in sources.items()}
    files[DECLARATION_PATH] = declaration(accepted, sources)
    return files


ENCLAVE: dict[str, dict[str, bytes]] = {
    COMMIT_V1_ONLY: enclave_tree([V1]),
    COMMIT_V1_AND_V2: enclave_tree([V1, V2]),
}


def source_from(trees: dict[str, dict[str, bytes]] | None = None):  # noqa: ANN201 - test helper
    table = ENCLAVE if trees is None else trees

    def _read(commit: str, path: str) -> bytes:
        if commit not in table or path not in table[commit]:
            # The real reader raises on a 404 exactly like this.
            raise ValueError(f"cannot read {path} at {commit} (HTTP 404)")
        return table[commit][path]

    return _read


def lister_from(trees: dict[str, dict[str, bytes]] | None = None):  # noqa: ANN201 - test helper
    """The package's real file list at a commit, as the contents API gives it.

    Deliberately derived from the fixture tree rather than from the
    declaration, because the property under test is that the declaration is
    checked against the PACKAGE and not against its own key set.
    """
    table = ENCLAVE if trees is None else trees
    prefix = f"{ENCLAVE_PACKAGE}/"

    def _list(commit: str) -> frozenset[str]:
        if commit not in table:
            raise ValueError(f"cannot list {ENCLAVE_PACKAGE} at {commit} (HTTP 404)")
        return frozenset(
            path[len(prefix) :]
            for path in table[commit]
            if path.startswith(prefix) and path.endswith(".go")
        )

    return _list


def gcp_record(**overrides: Any) -> dict[str, Any]:
    record: dict[str, Any] = {
        "platform": "gcp-confidential-space",
        "api_base_url": "https://api.trustedrouter.com/v1",
        "image_digest": GCP_DIGEST,
        "accepted_image_digests": [GCP_DIGEST],
        "source_commit": COMMIT_V1_AND_V2,
    }
    record.update(overrides)
    return record


def aws_record(**overrides: Any) -> dict[str, Any]:
    record: dict[str, Any] = {
        "platform": "aws-nitro-enclaves",
        "api_base_url": "https://api-aws.trustedrouter.com/v1",
        "pcr0": AWS_PCR0,
        "accepted_pcr0s": [AWS_PCR0],
        "source_commit": COMMIT_V1_AND_V2,
    }
    record.update(overrides)
    return record


def azure_record(**overrides: Any) -> dict[str, Any]:
    record: dict[str, Any] = {
        "platform": "azure-confidential-containers-sev-snp",
        "api_base_url": "https://api-azure.trustedrouter.com/v1",
        "hostdata": AZURE_UAEN,
        "accepted_hostdata": [AZURE_UAEN, AZURE_SEA],
        "attestation_issuers": [UAEN_ISSUER, SEA_ISSUER],
        "source_commit": COMMIT_V1_AND_V2,
        "regions": [
            {
                "attestation_url": UAEN_URL,
                "hostdata": AZURE_UAEN,
                "attestation_issuer": UAEN_ISSUER,
            },
            {
                "attestation_url": SEA_URL,
                "hostdata": AZURE_SEA,
                "attestation_issuer": SEA_ISSUER,
            },
        ],
    }
    record.update(overrides)
    return record


LIVE: dict[str, bytes] = {
    "https://api.trustedrouter.com/attestation": gcp_attestation(),
    "https://api-aws.trustedrouter.com/attestation": aws_attestation(),
    UAEN_URL: azure_attestation(AZURE_UAEN, UAEN_ISSUER),
    SEA_URL: azure_attestation(AZURE_SEA, SEA_ISSUER),
}


class FakeTransport(Transport):
    """The one seam scripts/verify_trust_measurements.py's samplers read through.

    Substituting here rather than stubbing the parsers is what keeps the two
    scripts sharing one COSE reader and one JWT reader: these fixtures are the
    bytes those parsers are given, not values handed past them.

    No peer certificate is returned, so `sample_aws_enclave` reports that the
    Nitro document's certificate binding is unverifiable. The check does not
    read that field and does not claim the AWS read is authenticated; see the
    module docstring under WHAT THIS DOES NOT ESTABLISH in the script.
    """

    def __init__(self, table: dict[str, bytes]) -> None:
        self.table = table

    def fetch(
        self, url: str, *, verify_tls: bool = True, want_peer_certificate: bool = False
    ) -> Fetched:
        if url not in self.table:
            raise ValueError(f"nothing serving {url}")
        return Fetched(self.table[url])


def transport_from(live: dict[str, bytes] | None = None) -> FakeTransport:
    return FakeTransport(LIVE if live is None else live)


def run(spec_name: str, record: dict[str, Any], written: frozenset[str], **kwargs: Any):  # noqa: ANN201
    return check_plane(
        PLANES[spec_name],
        record,
        written,
        transport=kwargs.pop("transport", transport_from()),
        source=kwargs.pop("source", source_from()),
        list_package=kwargs.pop("list_package", lister_from()),
        **kwargs,
    )


def problems(results: list[RegionResult]) -> str:
    return " | ".join(problem for result in results for problem in result.problems)


def module(source: str, path: str = "src/trusted_router/byok_crypto.py") -> dict[str, str]:
    return {path: source}


# --------------------------------------------------------------------------
# Happy path
# --------------------------------------------------------------------------


def test_every_cloud_clears_when_every_enclave_reads_what_the_plane_writes() -> None:
    results = gather(
        "https://trustedrouter.com",
        ["gcp", "aws", "azure"],
        frozenset({V2}),
        records=lambda path: {
            "/trust/gcp-release.json": gcp_record(),
            "/trust/aws-release.json": aws_record(),
            "/trust/azure-release.json": azure_record(),
        }[path],
        transport=transport_from(),
        source=source_from(),
        list_package=lister_from(),
    )

    assert [result.host for result in results] == [
        "api.trustedrouter.com",
        "api-aws.trustedrouter.com",
        "api-azure.trustedrouter.com",
        "api-azure-sea.trustedrouter.com",
    ], "all four serving regions must be checked, and Azure's two come from the record"
    assert all(result.ok for result in results), problems(results)
    assert all(result.accepts == frozenset({V1, V2}) for result in results)


def test_azure_regions_are_enumerated_from_the_record_not_from_this_file() -> None:
    # A region added to the record must be checked without a code change here.
    # The reverse — a region serving that the record omits — is what
    # test_a_region_serving_outside_the_record_blocks covers, and neither is
    # detectable if the region list is a constant.
    extra_url = "https://api-azure-nz.trustedrouter.com/attestation"
    record = azure_record()
    record["regions"].append(
        {
            "attestation_url": extra_url,
            "hostdata": "ab" * 32,
            "attestation_issuer": "https://trquillnz.nz.attest.azure.net",
        }
    )

    hosts = [region.host for region in regions_of(record, PLANES["azure"])]

    assert hosts == [
        "api-azure.trustedrouter.com",
        "api-azure-sea.trustedrouter.com",
        "api-azure-nz.trustedrouter.com",
    ]


def test_a_record_with_no_regions_array_is_one_region_not_zero() -> None:
    # GCP and AWS publish no `regions` array. Reading that as "no regions to
    # check" would make the check pass vacuously on the plane that carries every
    # prompt, which is the most expensive way to be green.
    regions = regions_of(gcp_record(), PLANES["gcp"])

    assert len(regions) == 1
    assert regions[0].attestation_url == "https://api.trustedrouter.com/attestation"


# --------------------------------------------------------------------------
# The outage case
# --------------------------------------------------------------------------


def test_enclave_reading_only_v1_blocks_a_plane_that_writes_v2() -> None:
    """The migration's §2.3 outage, as a fixture.

    An enclave at a pre-step-1 commit accepts only V1. The control plane build
    in front of it writes V2. Every BYOK key in that cloud's database stops
    opening at the next inference request. This is the case the check exists for
    and the one that must never come back green.
    """
    results = run("aws", aws_record(source_commit=COMMIT_V1_ONLY), frozenset({V2}))

    assert not results[0].ok
    assert "WRITES" in problems(results)
    assert V2 in problems(results)
    assert results[0].accepts == frozenset({V1})


def test_a_plane_still_writing_v1_clears_against_a_v1_only_enclave() -> None:
    # The subset is the law, not equality. A pre-step-2 control plane in front
    # of a pre-step-1 enclave is a legal deployment and must not be blocked, or
    # the check is just "refuse everything" wearing a table.
    results = run("aws", aws_record(source_commit=COMMIT_V1_ONLY), frozenset({V1}))

    assert results[0].ok, problems(results)


def test_an_enclave_ahead_of_the_plane_clears() -> None:
    # Step 1 shipped, step 2 has not. The enclave reads both; the plane writes
    # v1. That is the state §4.0 tells you to reach BEFORE landing step 2.
    results = run("gcp", gcp_record(), frozenset({V1}))

    assert results[0].ok, problems(results)


# --------------------------------------------------------------------------
# Fail-closed cases
# --------------------------------------------------------------------------


def test_missing_source_commit_blocks() -> None:
    """Absent provenance is a refusal, never a pass.

    The key is absent from aws-release.json and azure-release.json before the
    producer writes one, which is the shape fabricated here. What those two
    records actually served on 2026-08-16 is the neighbouring shape —
    `"source_commit": "not-configured"`, the producer's sentinel — and
    `test_a_source_commit_that_is_not_a_commit_blocks` covers that value. Both
    reach the same refusal, and that refusal is half of why the loud path
    cannot pass today, which is why the silent path exists. The other half is
    `test_a_commit_that_predates_the_declaration_blocks`, which is what GCP's
    published commit meets.
    """
    record = aws_record()
    del record["source_commit"]

    results = run("aws", record, frozenset({V2}))

    assert not results[0].ok
    assert "no source_commit" in problems(results)


@pytest.mark.parametrize("value", ["not-configured", "", "main", "HEAD", "v2.1.0"])
def test_a_source_commit_that_is_not_a_commit_blocks(value: str) -> None:
    # "not-configured" is the sentinel the producer writes when it cannot name
    # a commit; a branch or tag name resolves differently tomorrow than today,
    # which for a provenance field is the same as naming nothing.
    results = run("aws", aws_record(source_commit=value), frozenset({V2}))

    assert not results[0].ok


def test_a_measurement_outside_the_accepted_set_blocks() -> None:
    # Drift. verify_trust_measurements.py already reports this; here it must
    # also STOP the change, because a running build the record does not list is
    # a build whose accepted formats the record cannot describe.
    results = run(
        "gcp", gcp_record(accepted_image_digests=["sha256:" + "0b" * 32]), frozenset({V2})
    )

    assert not results[0].ok
    assert "not in the published accepted set" in problems(results)


def test_an_accepted_but_unmapped_measurement_blocks_mid_roll() -> None:
    """A bind window is two builds and one commit, so one of them is unverified.

    This is the sharp edge of the design and it is recorded rather than
    softened: during an enclave roll the check BLOCKS a format change. That is
    the ordering §4.0 asks for — roll the enclave out fully, then let the
    control plane take the new format — but it does mean an in-progress enclave
    release blocks a format-changing pull request, and whoever finds that
    surprising should read this test rather than widen the check.
    """
    outgoing = "sha256:" + "99" * 32
    record = gcp_record(accepted_image_digests=[outgoing, GCP_DIGEST], image_digest=outgoing)

    results = run("gcp", record, frozenset({V2}))

    assert not results[0].ok
    assert "bind window" in problems(results)


def test_an_accepted_measurement_no_region_served_blocks() -> None:
    """The live Azure mirror's exact shape: two accepted hostdata, no regions array.

    The check probes api-azure.trustedrouter.com, is never routed to the
    Southeast Asia enclave, and used to print "Every enclave serving azure
    accepts every format this build writes" over a sample of one. The second
    accepted measurement belongs to a build nothing here checked, so the run is
    a refusal, not a green with a footnote.
    """
    record = azure_record()
    del record["regions"]

    results = run("azure", record, frozenset({V2}))

    assert [result.host for result in results] == ["api-azure.trustedrouter.com", "-"]
    assert results[0].ok, "the region that did answer is fine; the coverage is not"
    assert not results[-1].ok
    assert "never checked" in problems(results)
    assert AZURE_SEA in problems(results)


def test_the_bind_window_refusal_does_not_depend_on_probe_routing() -> None:
    """The reviewer's narrowing of the bind-window claim, closed.

    `test_an_accepted_but_unmapped_measurement_blocks_mid_roll` fires only when
    the probe happens to be routed to the un-mapped build. Routed to the mapped
    one — the normal Traffic Manager or NLB primary — the record maps what is
    running and that check says nothing. The coverage refusal is what makes the
    outcome a property of the RECORD rather than of routing: the second accepted
    measurement was still never observed.
    """
    outgoing = "sha256:" + "99" * 32
    record = gcp_record(accepted_image_digests=[GCP_DIGEST, outgoing])

    results = run("gcp", record, frozenset({V2}))

    assert results[0].ok, "the live probe hit the mapped measurement, so this row clears"
    assert not results[-1].ok
    assert outgoing in problems(results)


def test_a_region_serving_outside_the_record_blocks() -> None:
    """A live region the record never described.

    Which region answers a shared Azure hostname is Traffic Manager's decision.
    A region brought up and routed to before its measurement was published
    answers with an MAA issuer the record does not name, and the check has no
    per-region entry for it — therefore no source_commit, therefore no accepted
    set. The honest answer is to refuse, not to fall back to the record-wide
    values and pretend the unlisted region is the listed one.
    """
    surprise = "https://trquillnz.nz.attest.azure.net"
    live = dict(LIVE)
    live[SEA_URL] = azure_attestation(AZURE_SEA, surprise)

    results = run("azure", azure_record(), frozenset({V2}), transport=transport_from(live))

    assert results[0].ok, "UAE North is untouched and must still clear"
    assert not results[1].ok
    assert "does not describe" in problems(results)


def test_an_unreachable_region_blocks_rather_than_being_skipped() -> None:
    # An attestation endpoint that does not answer is not evidence of anything.
    # verify_trust_measurements.py is allowed to skip; this is not.
    results = run("azure", azure_record(), frozenset({V2}), transport=transport_from({}))

    assert not any(result.ok for result in results)
    assert "cannot read a live attestation" in problems(results)


def test_an_unfetchable_declaration_blocks() -> None:
    def exploding(commit: str, path: str) -> bytes:
        raise ValueError(f"HTTP 404 for {path} at {commit}")

    results = run("gcp", gcp_record(), frozenset({V2}), source=exploding)

    assert not results[0].ok
    assert "404" in problems(results)


def test_a_commit_that_predates_the_declaration_blocks() -> None:
    """Every enclave released before this mechanism existed.

    There is no declaration to read at those commits, and the honest answer is
    that what they accept was never measured. The check refuses; the remedy is
    to roll an enclave built from a commit that carries one.
    """
    tree = {COMMIT_V1_AND_V2: {f"{ENCLAVE_PACKAGE}/cache.go": cache_go(accepts_v2=True)}}

    results = run("gcp", gcp_record(), frozenset({V2}), source=source_from(tree))

    assert not results[0].ok
    assert DECLARATION_PATH in problems(results)


def test_a_record_with_no_accepted_set_blocks() -> None:
    results = run("gcp", gcp_record(accepted_image_digests=[]), frozenset({V2}))

    assert not results[0].ok


def test_a_malformed_regions_array_blocks_the_whole_cloud() -> None:
    # Not "check the regions we could parse and pass". A record we cannot fully
    # read describes a deployment we cannot fully see, and partial coverage
    # reported as a pass is the failure this whole file is about.
    record = azure_record()
    record["regions"] = [{"attestation_url": "https://api-azure.trustedrouter.com/attestation"}]

    results = gather(
        "https://trustedrouter.com",
        ["azure"],
        frozenset({V2}),
        records=lambda path: record,  # noqa: ARG005
        transport=transport_from(),
        source=source_from(),
        list_package=lister_from(),
    )

    assert not results[0].ok
    assert "unreadable" in problems(results)


def test_an_unreadable_record_blocks_the_whole_cloud() -> None:
    results = gather(
        "https://trustedrouter.com",
        ["aws"],
        frozenset({V2}),
        records=lambda path: (_ for _ in ()).throw(ValueError(f"HTTP 404 for {path}")),
        transport=transport_from(),
        source=source_from(),
        list_package=lister_from(),
    )

    assert not results[0].ok
    assert "no usable release record" in problems(results)


# --------------------------------------------------------------------------
# ACCEPTS is behaviour the enclave repo measured, not syntax this file reads
# --------------------------------------------------------------------------


def test_a_case_label_is_not_acceptance() -> None:
    """The reviewer's four evasions, as one assertion at this boundary.

    An erroring case body, a kill switch ahead of the switch, a rejection in
    decryptEnvelope, and a renamed dispatch all produce the same pair: cache.go
    still contains `case AlgorithmV2:`, and a round trip through
    (*Cache).Resolve still fails. This fabricates that pair directly. The old
    parser read the label and returned {V1, V2}; the declaration says what the
    probe observed, and the change is blocked.
    """
    tree = {COMMIT_V1_ONLY: enclave_tree([V1], accepts_v2_label=True)}
    assert b"case AlgorithmV2:" in tree[COMMIT_V1_ONLY][f"{ENCLAVE_PACKAGE}/cache.go"]

    assert accepted_formats(COMMIT_V1_ONLY, source_from(tree), lister_from(tree)) == frozenset({V1})

    results = run(
        "aws",
        aws_record(source_commit=COMMIT_V1_ONLY),
        frozenset({V2}),
        source=source_from(tree),
    )
    assert not results[0].ok
    assert "ACCEPTS only" in problems(results)


def test_a_declaration_that_no_longer_matches_the_package_blocks() -> None:
    """A declaration is evidence about the package it was generated from.

    Edit cache.go without re-running the generator — which is what every one of
    the four evasions does — and the declaration describes a build that is not
    this one. The enclave repo's own test fails on that, and so does this: the
    pinned sha256 no longer matches the file at the same commit.
    """
    tampered = dict(ENCLAVE[COMMIT_V1_AND_V2])
    tampered[f"{ENCLAVE_PACKAGE}/cache.go"] = cache_go(accepts_v2=True).replace(
        b"return aadV2(namespaceProvider, workspaceID, provider)",
        b'return nil, errors.New("byokcache: v2 reads are not enabled in this build")',
    )

    with pytest.raises(ValueError, match="different build"):
        accepted_formats(
            COMMIT_V1_AND_V2,
            source_from({COMMIT_V1_AND_V2: tampered}),
            lister_from({COMMIT_V1_AND_V2: tampered}),
        )


def test_a_declaration_that_pins_only_part_of_the_package_blocks() -> None:
    """Verifying the pins it lists says nothing about the files it omits.

    The consumer used to iterate the declaration's own `source_sha256` keys, so
    a declaration pinning one unrelated file — correctly, at that commit —
    passed over a cache.go that had changed underneath it. The pin list is now
    checked against the package's real file list at that commit, and a subset
    is a refusal.
    """
    sources = {
        "cache.go": cache_go(accepts_v2=True),
        "kms_http_gcp.go": b"package byokcache\n\n// unrelated\n",
    }
    files = {f"{ENCLAVE_PACKAGE}/{name}": body for name, body in sources.items()}
    # The declaration pins only the unrelated file, and pins it correctly.
    files[DECLARATION_PATH] = declaration([V1, V2], {"kms_http_gcp.go": sources["kms_http_gcp.go"]})
    tree = {COMMIT_V1_AND_V2: files}

    with pytest.raises(ValueError, match="does not pin cache.go"):
        accepted_formats(COMMIT_V1_AND_V2, source_from(tree), lister_from(tree))


def test_a_package_listing_that_cannot_be_obtained_blocks() -> None:
    # Completeness that cannot be checked is completeness that was not checked.
    def exploding(commit: str) -> frozenset[str]:
        raise ValueError(f"cannot list the package at {commit} (HTTP 403)")

    with pytest.raises(ValueError, match="HTTP 403"):
        accepted_formats(COMMIT_V1_AND_V2, source_from(), exploding)


def test_an_empty_package_listing_blocks_rather_than_matching_vacuously() -> None:
    # "The declaration pins every file in an empty package" is true and worth
    # nothing, and it is what a listing bug would produce.
    with pytest.raises(ValueError, match="nothing the declaration could be bound to"):
        accepted_formats(COMMIT_V1_AND_V2, source_from(), lambda commit: frozenset())  # noqa: ARG005


def test_a_declaration_is_read_for_every_file_it_pins() -> None:
    # The pin is worth nothing if a pinned file that cannot be fetched is
    # treated as unchanged.
    incomplete = {COMMIT_V1_AND_V2: {DECLARATION_PATH: ENCLAVE[COMMIT_V1_AND_V2][DECLARATION_PATH]}}

    with pytest.raises(ValueError, match="cache.go"):
        accepted_formats(
            COMMIT_V1_AND_V2,
            source_from(incomplete),
            lister_from({COMMIT_V1_AND_V2: ENCLAVE[COMMIT_V1_AND_V2]}),
        )


@pytest.mark.parametrize(
    ("overrides", "reason"),
    [
        pytest.param({"schema": "something/else"}, "schema", id="unknown-schema"),
        pytest.param({"package": "enclave-go/internal/other"}, "package", id="wrong-package"),
        pytest.param({"accepted": []}, "no accepted formats", id="empty-accepted"),
        pytest.param({"accepted": [""]}, "non-empty strings", id="blank-format"),
        pytest.param({"accepted": [V1, 7]}, "non-empty strings", id="non-string-format"),
        pytest.param({"rejected_control": ""}, "rejected_control", id="no-control-value"),
        pytest.param({"source_sha256": {}}, "pins no source files", id="no-pins"),
        pytest.param(
            {"source_sha256": {"../../etc/passwd": "0" * 64}}, "not a .go file", id="path-escape"
        ),
        pytest.param({"source_sha256": {"cache.go": "nope"}}, "not a sha256", id="bad-digest"),
    ],
)
def test_a_declaration_this_script_cannot_read_blocks(
    overrides: dict[str, Any], reason: str
) -> None:
    # Never assume a superset. A declaration in a shape this script does not
    # understand is a build whose accepted set is unknown, and unknown blocks.
    sources = {"cache.go": cache_go(accepts_v2=True)}
    files = {f"{ENCLAVE_PACKAGE}/cache.go": sources["cache.go"]}
    files[DECLARATION_PATH] = declaration([V1, V2], sources, overrides)

    with pytest.raises(ValueError, match=reason):
        accepted_formats(
            COMMIT_V1_AND_V2,
            source_from({COMMIT_V1_AND_V2: files}),
            lister_from({COMMIT_V1_AND_V2: files}),
        )


def test_a_probe_that_accepted_its_own_control_value_blocks() -> None:
    """`accepted` means something only if the probe could have said no.

    A generator that accepts everything would list the control value too. That
    is not a build that accepts everything; it is a measurement of nothing.
    """
    sources = {"cache.go": cache_go(accepts_v2=True)}
    files = {f"{ENCLAVE_PACKAGE}/cache.go": sources["cache.go"]}
    files[DECLARATION_PATH] = declaration([V1, V2, CONTROL], sources)

    with pytest.raises(ValueError, match="cannot distinguish"):
        accepted_formats(
            COMMIT_V1_AND_V2,
            source_from({COMMIT_V1_AND_V2: files}),
            lister_from({COMMIT_V1_AND_V2: files}),
        )


def test_a_declaration_that_is_not_json_blocks() -> None:
    files = {
        f"{ENCLAVE_PACKAGE}/cache.go": cache_go(accepts_v2=True),
        DECLARATION_PATH: b"404: Not Found",
    }

    with pytest.raises(ValueError, match="not JSON"):
        accepted_formats(
            COMMIT_V1_AND_V2,
            source_from({COMMIT_V1_AND_V2: files}),
            lister_from({COMMIT_V1_AND_V2: files}),
        )


# --------------------------------------------------------------------------
# WRITES is derived from the whole write surface, or the check rots
# --------------------------------------------------------------------------


def test_written_formats_follow_the_source_not_a_constant_in_this_file() -> None:
    """A V3 write must be picked up with no edit to the checker.

    Hardcoding "the plane writes V2" is the failure that makes a check correct
    exactly once. Here a fabricated module writes a format that exists nowhere
    in the codebase, and the parser must report it.
    """
    source = (
        f'ALGORITHM_V3 = "{V3}"\n'
        "def seal():\n"
        "    return EncryptedSecretEnvelope(algorithm=ALGORITHM_V3, key_ref='k')\n"
    )

    assert written_formats(module(source)) == frozenset({V3})


def test_written_formats_reports_every_format_the_module_writes() -> None:
    source = (
        f'A = "{V1}"\n'
        f'B = "{V2}"\n'
        "def old():\n"
        "    return EncryptedSecretEnvelope(algorithm=A)\n"
        "def new():\n"
        "    return EncryptedSecretEnvelope(algorithm=B)\n"
    )

    assert written_formats(module(source)) == frozenset({V1, V2})


@pytest.mark.parametrize(
    ("body", "label"),
    [
        pytest.param(
            "_Envelope = EncryptedSecretEnvelope\n"
            "def seal():\n"
            "    return _Envelope(algorithm=ALGORITHM_V3)\n",
            "a module-level alias",
            id="alias",
        ),
        pytest.param(
            "def seal():\n"
            "    Envelope = EncryptedSecretEnvelope\n"
            "    return Envelope(algorithm=ALGORITHM_V3)\n",
            "an alias bound inside the function",
            id="local-alias",
        ),
        pytest.param(
            "class V3Envelope(EncryptedSecretEnvelope):\n"
            "    pass\n"
            "def seal():\n"
            "    return V3Envelope(algorithm=ALGORITHM_V3)\n",
            "a subclass",
            id="subclass",
        ),
        pytest.param(
            "import dataclasses\n"
            "def seal(envelope):\n"
            "    return dataclasses.replace(envelope, algorithm=ALGORITHM_V3)\n",
            "dataclasses.replace",
            id="replace",
        ),
        pytest.param(
            "from dataclasses import replace\n"
            "def seal(envelope):\n"
            "    return replace(envelope, algorithm=ALGORITHM_V3)\n",
            "an imported replace",
            id="bare-replace",
        ),
        pytest.param(
            "_Envelope: type[EncryptedSecretEnvelope] = EncryptedSecretEnvelope\n"
            "def seal():\n"
            "    return _Envelope(algorithm=ALGORITHM_V3)\n",
            "an ANNOTATED module-level alias -- one type annotation away from the plain alias "
            "above, in a repo that runs mypy over 240 files",
            id="annotated-alias",
        ),
    ],
)
def test_written_formats_sees_a_v3_written_through_an_indirection(body: str, label: str) -> None:
    """Each of these returned {V2} while the build wrote V3.

    The first five come from the review of the first parser, which matched a
    callee spelled exactly EncryptedSecretEnvelope. The annotated alias comes
    from the review of the SECOND parser, which closed the name set over
    ast.Assign and never looked at ast.AnnAssign. A check that can be stepped
    around by adding a type annotation is a check about spelling.
    """
    source = f'ALGORITHM_V3 = "{V3}"\n' + body

    assert written_formats(module(source)) == frozenset({V3}), label


@pytest.mark.parametrize(
    ("sibling", "call", "label"),
    [
        pytest.param(
            "from trusted_router.storage_models import EncryptedSecretEnvelope\n"
            "Envelope = EncryptedSecretEnvelope\n",
            "Envelope",
            "an alias defined in a sibling module and imported",
            id="cross-module-alias",
        ),
        pytest.param(
            "from trusted_router.storage_models import EncryptedSecretEnvelope\n"
            "class V3Envelope(EncryptedSecretEnvelope):\n"
            "    pass\n",
            "V3Envelope",
            "a subclass defined in a sibling module and imported",
            id="cross-module-subclass",
        ),
    ],
)
def test_written_formats_closes_the_name_set_across_modules(
    sibling: str, call: str, label: str
) -> None:
    """The constructor-name closure is over the surface, not over one file.

    The second review's whole method here was to move the alias or the subclass
    one module away. `_constructor_names` took a single tree, so a name defined
    in `v3_models.py` and imported into `byok_crypto.py` was simply not in the
    set, and the call fell through in silence while the build wrote V3.
    """
    sources = {
        "src/trusted_router/v3_models.py": sibling,
        "src/trusted_router/byok_crypto.py": (
            f'ALGORITHM_V3 = "{V3}"\n'
            f"from trusted_router.v3_models import {call}\n"
            "def seal():\n"
            f"    return {call}(algorithm=ALGORITHM_V3)\n"
        ),
    }

    assert written_formats(sources) == frozenset({V3}), label


def test_written_formats_sees_a_write_site_in_any_module() -> None:
    # The first version opened src/trusted_router/byok_crypto.py and nothing
    # else, so a V3 write in a new module was invisible.
    sources = {
        "src/trusted_router/byok_crypto.py": (
            f'ALGORITHM_V2 = "{V2}"\n'
            "def seal():\n"
            "    return EncryptedSecretEnvelope(algorithm=ALGORITHM_V2)\n"
        ),
        "src/trusted_router/broadcast_crypto.py": (
            f'ALGORITHM_V3 = "{V3}"\n'
            "def seal():\n"
            "    return EncryptedSecretEnvelope(algorithm=ALGORITHM_V3)\n"
        ),
    }

    assert written_formats(sources) == frozenset({V2, V3})


@pytest.mark.parametrize(
    ("body", "reason"),
    [
        pytest.param(
            "    envelope.algorithm = ALGORITHM_V3\n", "assigns an `algorithm` attribute", id="attr"
        ),
        pytest.param(
            "    setattr(envelope, 'algorithm', ALGORITHM_V3)\n",
            "through setattr",
            id="setattr",
        ),
        pytest.param(
            "    object.__setattr__(envelope, 'algorithm', ALGORITHM_V3)\n",
            "through __setattr__",
            id="object-setattr",
        ),
        pytest.param(
            "    envelope.__dict__['algorithm'] = ALGORITHM_V3\n",
            "__dict__",
            id="dunder-dict",
        ),
    ],
)
def test_written_formats_refuses_a_format_assigned_after_construction(
    body: str, reason: str
) -> None:
    """`envelope.algorithm = ALGORITHM_V3` writes V3 and no constructor says so.

    EncryptedSecretEnvelope is a plain, non-frozen dataclass, so all four of
    these run. Only the first was refused: `setattr`, `object.__setattr__` and
    a direct `__dict__` write are the same mutation spelled differently, and
    they were silently ignored while the second review used them.
    """
    source = f'ALGORITHM_V3 = "{V3}"\ndef seal(envelope):\n{body}    return envelope\n'

    with pytest.raises(ValueError, match=reason):
        written_formats(module(source))


def test_the_algorithm_refusal_is_deliberately_over_broad() -> None:
    """It cannot tell an envelope from a JWT header, and the message says so.

    A narrower rule would have to decide which objects are envelopes, which is
    the inference this scan exists because it cannot make. Being wrong in this
    direction is a refusal a human clears by reading one line; being wrong in
    the other is a silent green over a V3 write. The cost is real and is stated
    here rather than discovered: an unrelated `self.algorithm = "RS256"`
    anywhere under src/trusted_router makes the written set underivable, and
    `test_an_underivable_write_side_fails_the_check` is what that then does to
    the pull request that added it.
    """
    sources = {
        "src/trusted_router/byok_crypto.py": (
            f'ALGORITHM_V2 = "{V2}"\n'
            "def seal():\n"
            "    return EncryptedSecretEnvelope(algorithm=ALGORITHM_V2)\n"
        ),
        "src/trusted_router/jwt_helper.py": (
            "class SigningHeader:\n    def __init__(self):\n        self.algorithm = 'RS256'\n"
        ),
    }

    with pytest.raises(ValueError, match="cannot tell whether that object is an envelope"):
        written_formats(sources)


@pytest.mark.parametrize(
    "handover",
    [
        pytest.param(
            "make = functools.partial(EncryptedSecretEnvelope, algorithm=ALGORITHM_V3)\n",
            id="bare-name",
        ),
        pytest.param(
            "import trusted_router.storage_models as storage_models\n"
            "make = functools.partial(storage_models.EncryptedSecretEnvelope)\n",
            id="dotted",
        ),
    ],
)
def test_written_formats_refuses_the_constructor_used_as_a_value(handover: str) -> None:
    """functools.partial, a factory table, a registry.

    The format written through one of those is chosen somewhere this parser
    does not look. Only the bare-Name handover was refused; the dotted form
    passed cleanly, so the fail-closed half of the indirection guard was
    asymmetric and the asymmetry was one attribute access wide.
    """
    source = "import functools\n" + f'ALGORITHM_V3 = "{V3}"\n' + handover

    with pytest.raises(ValueError, match="indirection"):
        written_formats(module(source))


@pytest.mark.parametrize(
    "source",
    [
        pytest.param(
            "def seal(alg):\n    return EncryptedSecretEnvelope(algorithm=alg)\n",
            id="algorithm-is-a-parameter",
        ),
        pytest.param(
            "def seal(kw):\n    return EncryptedSecretEnvelope(**kw)\n",
            id="kwargs-splat-outside-the-rehydration-modules",
        ),
        pytest.param(
            "def seal(stored, alg):\n"
            "    return EncryptedSecretEnvelope(**{**stored, 'algorithm': alg})\n",
            id="mapping-display-splat",
        ),
        pytest.param(
            "def seal():\n    return EncryptedSecretEnvelope(key_ref='k')\n",
            id="no-algorithm-at-all",
        ),
        pytest.param(
            "def seal(alg):\n    return EncryptedSecretEnvelope(alg, key_ref='k')\n",
            id="positional",
        ),
        pytest.param("X = 1\n", id="constructor-gone"),
    ],
)
def test_written_formats_fails_closed_when_it_cannot_derive_the_format(source: str) -> None:
    # An unreadable write side is not a safe write side. Returning an empty set
    # would make every subset check pass trivially, which is the worst possible
    # way for this to fail.
    with pytest.raises(ValueError):
        written_formats(module(source))


def test_a_rehydration_site_is_allowed_only_where_it_rebuilds_a_stored_row() -> None:
    """`EncryptedSecretEnvelope(**stored)` reads a format, it does not choose one.

    Two modules do this today and both are rebuilding a database row. The
    allowlist is a refusal boundary, not a rule: the same shape anywhere else
    refuses until someone decides which kind it is. This asserts both halves.
    """
    rebuild = "def rebuild(stored):\n    return EncryptedSecretEnvelope(**stored)\n"
    write = f'ALGORITHM_V2 = "{V2}"\ndef seal():\n    return EncryptedSecretEnvelope(algorithm=ALGORITHM_V2)\n'  # noqa: E501

    scan = scan_write_surface(
        {
            "src/trusted_router/storage_models.py": rebuild,
            "src/trusted_router/byok_crypto.py": write,
        }
    )
    assert scan.formats == frozenset({V2})
    assert scan.rehydration_sites == ("src/trusted_router/storage_models.py:2",)

    with pytest.raises(ValueError, match="_REHYDRATION_MODULES"):
        written_formats({"src/trusted_router/storage_gcp.py": rebuild, **module(write)})


def test_the_real_write_surface_writes_exactly_v2_today() -> None:
    # Pins the current answer so a change to the write side is visible in a
    # diff, without the check itself depending on that answer. Also pins the
    # rehydration sites: a new one appears here before it appears in
    # production, and it is the one shape the scan reads no format from.
    #
    # The line numbers are deliberately dropped. An earlier version asserted
    # the full "file:line" strings and went red on this branch the moment main
    # gained an unrelated 14-line change to storage_models.py -- the sites had
    # not moved, the file above them had. A canary that fires on every edit to
    # a file it is only watching three lines of is a canary that gets deleted,
    # which is the failure mode this whole check is written against. Comparing
    # the files, with multiplicity, still names a NEW rehydration site the
    # moment one appears and is stable under edits that are not one.
    scan = scan_write_surface(read_write_surface())

    assert scan.formats == frozenset({V2})
    assert tuple(site.rsplit(":", 1)[0] for site in scan.rehydration_sites) == (
        "src/trusted_router/byok_aad_backfill.py",
        "src/trusted_router/storage_models.py",
        "src/trusted_router/storage_models.py",
        "src/trusted_router/storage_models.py",
    )


def test_an_unparseable_module_blocks() -> None:
    with pytest.raises(ValueError, match="cannot parse"):
        written_formats(module("def seal(:\n"))


# --------------------------------------------------------------------------
# WRITES is primarily BEHAVIOUR: what calling this tree actually produced
# --------------------------------------------------------------------------


def test_the_probe_reports_the_format_a_real_call_produced() -> None:
    """The write-side twin of the enclave's declaration, on the real modules.

    Both write entry points are called for real against a local AES wrapper,
    and the format is read off the envelope objects those calls constructed.
    Nothing here parses anything, which is the point: every spelling that
    defeated the scan twice — an alias, a subclass, dataclasses.replace, an
    assignment to .algorithm, a sibling module — converges on the same object
    and the same attribute value.
    """
    observed = probe_write_entry_points()

    assert observed.formats == frozenset({V2})
    assert dict(observed.by_entry_point) == {
        "src/trusted_router/byok_crypto.py:encrypt_byok_secret": (V2,),
        "src/trusted_router/byok_crypto.py:encrypt_control_secret": (V2,),
    }


def test_the_probe_reads_the_object_and_not_the_call_that_made_it() -> None:
    """A format assigned AFTER construction is the value the probe reports.

    This is the shape the scan can only refuse on: `envelope.algorithm = V3`
    with the constructor still saying V2. The probe holds the object, reads it
    once the entry point has returned, and reports V3.
    """

    def mutating_entry_point(settings: Any) -> object:  # noqa: ARG001 - matches the probe signature
        from trusted_router.byok_crypto import ALGORITHM_V2
        from trusted_router.storage_models import EncryptedSecretEnvelope

        envelope = EncryptedSecretEnvelope(
            algorithm=ALGORITHM_V2,
            key_ref="k",
            encrypted_dek="",
            dek_nonce="",
            ciphertext="",
            nonce="",
        )
        envelope.algorithm = V3
        return envelope

    observed = probe_write_entry_points({"fabricated:mutating": mutating_entry_point})

    assert observed.formats == frozenset({V3})


class _SwallowsInitPatch(type):
    """A class whose `__init__` cannot be replaced, and says nothing about it.

    Fabricates the one failure the probe's control exists to catch: the
    recorder is installed, the install silently does nothing, and every
    subsequent observation is empty. An empty observation from a blind recorder
    reads exactly like "this build writes no new format".
    """

    def __setattr__(cls, name: str, value: Any) -> None:
        if name == "__init__":
            return
        super().__setattr__(name, value)


class _UnrecordableEnvelope(metaclass=_SwallowsInitPatch):
    def __init__(self, **fields: Any) -> None:
        self.__dict__.update(fields)


def test_the_probe_refuses_when_its_recorder_is_blind() -> None:
    """A recorder that sees nothing reports "no V3" for a build that writes V3.

    So the recorder is shown a format before it is trusted to report one: an
    envelope carrying PROBE_CONTROL_FORMAT is constructed and must come back.
    This is the same argument as the declaration's `rejected_control`, and the
    same sentinel string.
    """
    with pytest.raises(ValueError, match="did not observe its own control envelope"):
        probe_write_entry_points(
            {"fabricated:never-reached": lambda settings: None},  # noqa: ARG005
            envelope_type=_UnrecordableEnvelope,
        )


def test_the_probe_reads_the_value_the_entry_point_returned() -> None:
    """The one cover for an entry point that builds a LOOK-ALIKE, not the patched class.

    `probe_write_entry_points`' own docstring says so in as many words: the
    control proves the recorder fires for constructions of the class this
    function patched, and it does NOT prove an entry point builds that class —
    "what covers that is reading the value each entry point returns as well".

    That read was decorative when it landed. Deleting `returned_algorithm` from
    the probe left the whole file green, so the sentence above was an
    unenforced claim about the code. This is the world it describes: an entry
    point that constructs something else entirely, so `constructed` is empty
    and the returned object is the only witness. Without the return read this
    raises "produced no envelope"; with it, V3.
    """

    class LookAlikeEnvelope:
        def __init__(self, algorithm: str) -> None:
            self.algorithm = algorithm

    def builds_a_look_alike(settings: Any) -> object:  # noqa: ARG001 - matches the probe signature
        return LookAlikeEnvelope(algorithm=V3)

    observed = probe_write_entry_points({"fabricated:look-alike": builds_a_look_alike})

    assert observed.formats == frozenset({V3})
    assert observed.by_entry_point == (("fabricated:look-alike", (V3,)),)

    # And it is not a way to smuggle the control value past the sentinel check.
    with pytest.raises(ValueError, match="produced the probe's own control value"):
        probe_write_entry_points(
            {"fabricated:look-alike": lambda settings: LookAlikeEnvelope(PROBE_CONTROL_FORMAT)}  # noqa: ARG005
        )


def test_a_probe_that_cannot_call_its_entry_point_refuses() -> None:
    # A probe that raises is not evidence that the path writes nothing; it is a
    # path whose written format was not measured, and deleting the probe to
    # make the check green is the failure mode this message names.
    def exploding(settings: Any) -> object:  # noqa: ARG001 - matches the probe signature
        raise RuntimeError("no key material here")

    with pytest.raises(ValueError, match="could not be called by the probe"):
        probe_write_entry_points({"fabricated:exploding": exploding})


def test_a_probe_that_produced_no_envelope_refuses() -> None:
    with pytest.raises(ValueError, match="produced no envelope"):
        probe_write_entry_points({"fabricated:silent": lambda settings: None})  # noqa: ARG005


def test_an_entry_point_that_produced_the_control_value_refuses() -> None:
    """The control string must stay a fixture, never an observation.

    If a real call can produce PROBE_CONTROL_FORMAT, the probe can no longer
    tell its own scaffolding from a write, and the union it feeds the subset
    check would carry a format no enclave will ever accept.
    """

    def leaks_the_control(settings: Any) -> object:  # noqa: ARG001 - matches the probe signature
        from trusted_router.storage_models import EncryptedSecretEnvelope

        return EncryptedSecretEnvelope(
            algorithm=PROBE_CONTROL_FORMAT,
            key_ref="k",
            encrypted_dek="",
            dek_nonce="",
            ciphertext="",
            nonce="",
        )

    with pytest.raises(ValueError, match="produced the probe's own control value"):
        probe_write_entry_points({"fabricated:leaky": leaks_the_control})


def test_an_entry_point_with_no_probe_is_a_refusal() -> None:
    """The enumeration closure, which is what makes the probe's coverage real.

    A behavioural probe is only as good as the set of paths it calls, and "we
    called the important ones" is the claim that rots. So the entry points are
    read out of the source — every function under src/trusted_router whose
    return annotation names the envelope type — and one that `_WRITE_PROBES`
    does not call refuses. It is the same closure the enclave probe applies to
    algorithm constants it does not know how to seal.
    """
    sources = {
        "src/trusted_router/byok_crypto.py": (
            f'ALGORITHM_V2 = "{V2}"\n'
            "def encrypt_byok_secret(a, b) -> EncryptedSecretEnvelope:\n"
            "    return EncryptedSecretEnvelope(algorithm=ALGORITHM_V2)\n"
        ),
        "src/trusted_router/broadcast_crypto.py": (
            "def seal_broadcast(a) -> EncryptedSecretEnvelope | None:\n    return None\n"
        ),
    }

    with pytest.raises(ValueError, match="no behavioural probe calls them"):
        derive_written_formats(sources, probe=lambda: WriteProbe(frozenset({V2}), ()))


def test_two_entry_points_sharing_a_name_in_one_module_refuse() -> None:
    # One probe key would stand for both, so one of them would go unmeasured
    # while the table looked complete.
    sources = {
        "src/trusted_router/byok_crypto.py": (
            f'ALGORITHM_V2 = "{V2}"\n'
            "def seal(a) -> EncryptedSecretEnvelope:\n"
            "    return EncryptedSecretEnvelope(algorithm=ALGORITHM_V2)\n"
            "def seal(a, b) -> EncryptedSecretEnvelope:\n"
            "    return EncryptedSecretEnvelope(algorithm=ALGORITHM_V2)\n"
        )
    }

    with pytest.raises(ValueError, match="share a name inside one module"):
        derive_written_formats(sources, probe=lambda: WriteProbe(frozenset({V2}), ()))


def test_a_pep695_type_alias_annotation_is_not_enumerated() -> None:
    """A known, checked hole in the enumeration, recorded rather than implied.

    `type Env = EncryptedSecretEnvelope` parses to `ast.TypeAlias`, which the
    constructor-name closure does not read, so `-> Env` does not register as a
    write entry point and no probe is demanded for it. It is not a fail-open by
    itself — the write inside still has to get past the syntactic scan — but it
    is the shape that demotes a path to scan-only coverage without saying so,
    and the docstring on `_write_entry_points` says so because this assertion is
    what keeps that sentence honest.
    """
    source = (
        f'ALGORITHM_V2 = "{V2}"\n'
        "type Env = EncryptedSecretEnvelope\n"
        "def seal() -> Env:\n"
        "    return EncryptedSecretEnvelope(algorithm=ALGORITHM_V2)\n"
    )
    plain = (
        f'ALGORITHM_V2 = "{V2}"\n'
        "Env = EncryptedSecretEnvelope\n"
        "def seal() -> Env:\n"
        "    return Env(algorithm=ALGORITHM_V2)\n"
    )

    assert scan_write_surface(module(source)).entry_points == ()
    assert scan_write_surface(module(plain)).entry_points == (
        "src/trusted_router/byok_crypto.py:seal",
    )


def test_the_real_tree_has_a_probe_for_every_entry_point_it_declares() -> None:
    # The closure above is worth nothing if the real tree does not satisfy it.
    # This is the assertion that goes red the day someone adds a third
    # `-> EncryptedSecretEnvelope` function without a probe.
    scan = scan_write_surface(read_write_surface())

    assert scan.entry_points == (
        "src/trusted_router/byok_crypto.py:encrypt_byok_secret",
        "src/trusted_router/byok_crypto.py:encrypt_control_secret",
    )
    assert set(scan.entry_points) == set(gate._WRITE_PROBES)


def test_the_check_uses_the_union_of_the_two_derivations() -> None:
    """Union, because each derivation is blind where the other is not.

    A format only the probe saw is a write through an indirection no parser
    followed; a format only the scan saw is a write path nothing exercised.
    Taking either alone discards one of those. Taking the union can only make
    `written ⊆ accepted` harder to satisfy, which is the direction a check is
    allowed to be wrong in.
    """
    sources = {
        "src/trusted_router/byok_crypto.py": (
            f'ALGORITHM_V2 = "{V2}"\n'
            "def seal():\n"
            "    return EncryptedSecretEnvelope(algorithm=ALGORITHM_V2)\n"
        )
    }

    derivation = derive_written_formats(sources, probe=lambda: WriteProbe(frozenset({V3}), ()))

    assert derivation.behavioural == frozenset({V3})
    assert derivation.syntactic == frozenset({V2})
    assert derivation.formats == frozenset({V2, V3})


def test_the_real_tree_writes_exactly_v2_by_both_derivations() -> None:
    # Pins the current answer end to end, so a change to the write side is
    # visible in a diff without the check depending on the answer.
    derivation = derive_written_formats(read_write_surface())

    assert derivation.behavioural == frozenset({V2})
    assert derivation.syntactic == frozenset({V2})
    assert derivation.formats == frozenset({V2})
    assert PROBE_CONTROL_FORMAT not in derivation.formats


# --------------------------------------------------------------------------
# The baseline, and the two paths it routes between
# --------------------------------------------------------------------------


def test_the_baseline_matches_what_this_tree_writes() -> None:
    """MANDATORY. Without this assertion the design in the script is unsound.

    `main()` is silent — no record fetched, no enclave contacted — exactly when
    the derived written set equals BASELINE_WRITTEN_FORMATS. That constant is
    hand-maintained, and a hand-maintained constant that has drifted from what
    the tree writes makes the check silent about a real format change: it would
    compare V3 against a stale {V2} and take the loud path for the wrong reason,
    or, worse, a baseline edited to match a V3 write nobody verified would make
    every later run silent about it.

    So the constant is not believed. The real derivation runs against the real
    tree here and the two must be equal, which means the commit that changes
    what this tree writes cannot also leave the baseline stale: one of the two
    assertions fails until both edits are present, and the loud path has run on
    the commit in between.
    """
    derived = derive_written_formats(read_write_surface()).formats

    assert derived == BASELINE_WRITTEN_FORMATS, (
        "BASELINE_WRITTEN_FORMATS in scripts/check_format_ordering.py no longer equals what "
        "this tree writes. If this change is deliberate, the loud path must have cleared for "
        "every cloud on this commit BEFORE the constant is updated to match."
    )


def drive_main(
    monkeypatch: pytest.MonkeyPatch,
    argv: list[str],
    *,
    records: dict[str, dict[str, Any]] | None = None,
) -> int:
    """Run the REAL main() over the fabricated world, with no network.

    Only the four I/O seams are replaced — record fetch, the transport the
    attestation samplers read through, enclave file read, enclave package
    listing. Everything else, including the write derivation against this
    working tree, is the production path.
    """
    table = records or {
        "/trust/aws-release.json": aws_record(source_commit=COMMIT_V1_ONLY),
        "/trust/gcp-release.json": gcp_record(),
    }
    monkeypatch.setattr(gate, "fetch_record", lambda plane, path: table[path])  # noqa: ARG005
    monkeypatch.setattr(gate, "NetworkTransport", transport_from)
    monkeypatch.setattr(gate, "fetch_enclave_file", source_from())
    monkeypatch.setattr(gate, "fetch_enclave_package_files", lister_from())
    return gate.main(argv)


def surface_writing_v3() -> dict[str, str]:
    """The real write surface plus one module that writes a third format.

    A new module with a new module-level constant is how a v3 migration
    actually starts, and it is what the syntactic scan reads. It is not the same
    thing as editing byok_crypto.py to write V3 through the real key path — that
    is the empirical demonstration this check was proved with, and it cannot be
    a committed test because a tree that writes V3 fails
    `test_the_baseline_matches_what_this_tree_writes` by construction.
    """
    surface = dict(read_write_surface())
    surface["src/trusted_router/byok_crypto_v3.py"] = (
        f'ALGORITHM_V3 = "{V3}"\n'
        "def seal():\n"
        "    return EncryptedSecretEnvelope(algorithm=ALGORITHM_V3)\n"
    )
    return surface


def test_an_unchanged_write_side_is_silent_and_reads_no_network(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """The path every ordinary pull request takes, proved by breaking the network.

    The requirement is not "it happens to pass today". It is that a pull request
    which does not change the written format set cannot be reddened by anything
    outside this repository — and today that matters concretely, because the AWS
    and Azure records publish no `source_commit`, so the loud path CANNOT clear
    for them (see `test_missing_source_commit_blocks`). If the silent path
    touched the network at all, this check would be red on every pull request
    within a week of landing and deleted the week after.

    So every seam that could reach outside this process is replaced by a
    function that raises, including `gather` itself. Exit 0 with all of them
    armed is the proof that none of them was called.
    """

    def unreachable(*args: Any, **kwargs: Any) -> Any:
        raise AssertionError("the silent path must not perform any network I/O")

    for name in (
        "_fetch",
        "fetch_record",
        "fetch_enclave_file",
        "fetch_enclave_package_files",
        "NetworkTransport",
        "gather",
    ):
        monkeypatch.setattr(gate, name, unreachable)

    assert gate.main([]) == 0

    out = capsys.readouterr().out
    assert "no attestation endpoint was contacted" in out
    assert "BLOCKED" not in out


def test_a_new_written_format_takes_the_loud_path_and_blocks(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """A format the enclaves do not accept: named, with the cloud that cannot read it.

    Both fabricated clouds are checked. AWS is at a pre-step-1 commit and
    accepts only V1, so it blocks on V2 and V3; GCP accepts V1 and V2 and blocks
    on V3 alone. The output has to name the unreadable format and the cloud,
    because an author who cannot tell which cloud refused has no next step.
    """
    monkeypatch.setattr(gate, "read_write_surface", surface_writing_v3)

    exit_code = drive_main(monkeypatch, ["--cloud", "aws", "--cloud", "gcp"])
    out = capsys.readouterr().out

    assert exit_code == 1
    assert "THIS CHANGE ALTERS THE WRITTEN ENVELOPE FORMAT SET: V2 -> V2,V3" in out
    assert "BLOCKED aws/api-aws.trustedrouter.com" in out
    assert "BLOCKED gcp/api.trustedrouter.com" in out
    assert f"Unreadable: {V2}, {V3}" in out, "AWS reads neither"
    assert f"Unreadable: {V3}" in out, "GCP reads V2 but not V3"
    assert "BLOCKED: 2 serving region(s) refuse this format change" in out


def test_a_changed_format_with_an_unresolvable_cloud_refuses(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """Fail closed: a cloud whose declaration cannot be resolved is not assumed.

    The record here is the live shape of aws-release.json and
    azure-release.json, copied from what trustedrouter.com served on 2026-08-16:
    everything present and correct except `source_commit`, which is the
    producer's `"not-configured"` sentinel. The written set HAS changed, so this
    is the loud path, and the enclave behind that endpoint might well read V3.
    Nothing here can find out, and "cannot find out" must never render as a
    pass.
    """
    monkeypatch.setattr(gate, "read_write_surface", surface_writing_v3)
    unprovenanced = aws_record(source_commit="not-configured")

    exit_code = drive_main(
        monkeypatch, ["--cloud", "aws"], records={"/trust/aws-release.json": unprovenanced}
    )
    out = capsys.readouterr().out

    assert exit_code == 1
    assert "record carries no source_commit" in out
    assert "BLOCKED: 1 serving region(s) refuse this format change" in out


def test_a_changed_format_every_enclave_accepts_clears_and_asks_for_the_baseline(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """The loud path is not "refuse everything": V2 over a V1/V2 enclave clears.

    It also has to tell the author what to do next, because a cleared loud path
    leaves the baseline stale and every later pull request would take this same
    network path until it is updated.
    """
    monkeypatch.setattr(gate, "BASELINE_WRITTEN_FORMATS", frozenset({V1}))

    exit_code = drive_main(monkeypatch, ["--cloud", "gcp"])
    out = capsys.readouterr().out

    assert exit_code == 0
    assert "1 serving region(s) checked for gcp" in out
    assert "Now set BASELINE_WRITTEN_FORMATS to {'TR-BYOK-ENVELOPE-AES-256-GCM-V2'}" in out


def test_an_underivable_write_side_fails_the_check(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """Unknown is not unchanged, so it cannot take the silent path.

    `scan_write_surface` refuses on any assignment to an `algorithm` attribute
    anywhere under src/trusted_router, which an unrelated refactor can trip.
    That pull request goes red here, and the cost is stated rather than
    discovered: the message names the file and the line. The previous version of
    this program shipped a report-only mode precisely so this condition could
    not stop anything, because it was wired into deploy on three clouds. It is
    wired into one CI job now, so the refusal costs one pull request and the
    author of the change is the person reading it.
    """
    surface = dict(read_write_surface())
    surface["src/trusted_router/jwt_helper.py"] = (
        'class SigningHeader:\n    def __init__(self) -> None:\n        self.algorithm = "RS256"\n'
    )
    monkeypatch.setattr(gate, "read_write_surface", lambda: surface)

    assert drive_main(monkeypatch, ["--cloud", "gcp"]) == 1

    captured = capsys.readouterr()
    assert "FAILED, and not by a cloud" in captured.err
    assert "cannot determine what this build writes" in captured.err
    assert "jwt_helper.py" in captured.err
    # It must not read as a cleared run.
    for reads_like_a_pass in ("region(s) checked for", "every format this build writes"):
        assert reads_like_a_pass not in captured.err, reads_like_a_pass


def test_an_unparseable_module_fails_the_check_rather_than_being_silent(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    # The same routing rule at a second entry: a module that will not parse is a
    # written set that is unknown, and unknown is never treated as unchanged.
    monkeypatch.setattr(
        gate, "read_write_surface", lambda: {"src/trusted_router/x.py": "def f(:\n"}
    )

    assert drive_main(monkeypatch, ["--cloud", "gcp"]) == 1
    assert "cannot parse" in capsys.readouterr().err


# --------------------------------------------------------------------------
# Output
# --------------------------------------------------------------------------


def test_the_table_names_the_blocked_region_and_the_reason() -> None:
    # An author reads this at the moment a check goes red. If it does not say
    # which region and why, the next step is to disable the check.
    results = run("aws", aws_record(source_commit=COMMIT_V1_ONLY), frozenset({V2}))

    table = render(results, frozenset({V2}))

    assert "BLOCKED" in table
    assert "api-aws.trustedrouter.com" in table
    assert COMMIT_V1_ONLY in table
    assert "V1" in table


def test_a_measurement_that_was_read_never_renders_as_unknown() -> None:
    """ "-" in this table means NOT READ.

    The column elided anything 20 characters or shorter to "-", so a short
    measurement that was successfully read printed identically to one that was
    never obtained — in the author-facing table of a fail-closed check, where
    every other "-" means unknown.
    """
    short = RegionResult(cloud="gcp", host="api.example.com", measurement="sha256:abc")
    unread = RegionResult(cloud="gcp", host="api.example.com", problems=["cannot read"])

    table = render([short, unread], frozenset({V2}))

    assert "sha256:abc" in table
    assert table.count("-  ") >= 1, "the unread row still renders its measurement as -"
