"""Write src/trusted_router/static/tokens.css from the brand token kit.

The kit (docs/brand/trustedrouter-brand-tokens.json) is the design source of
truth. tokens.css is generated, never edited by hand: change the kit, rerun

    python scripts/build_tokens_css.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KIT = ROOT / "docs/brand/trustedrouter-brand-tokens.json"
OUT = ROOT / "src/trusted_router/static/tokens.css"


def build() -> str:
    kit = json.loads(KIT.read_text())
    meta = kit["meta"]
    header = (
        "/* Generated by scripts/build_tokens_css.py from "
        f"{KIT.relative_to(ROOT)} (v{meta['version']}, {meta['date']}).\n"
        " * Do not edit by hand. */\n"
    )
    # The repo's stylelint config wants modern colour notation (rgb with alpha).
    block = kit["css_custom_properties"].replace("rgba(", "rgb(")
    return header + block.rstrip() + "\n"


def main() -> None:
    OUT.write_text(build())
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
