#!/usr/bin/env python3
"""Refuse to deploy a control plane that writes an envelope format its enclaves cannot read.

    uv run python -m scripts.check_format_ordering
    uv run python -m scripts.check_format_ordering --cloud gcp

THE INVARIANT
-------------
A control plane may deploy only a build whose set of WRITTEN BYOK envelope
formats is a subset of the formats accepted by EVERY enclave serving that cloud.

Violate it and the damage is immediate and customer-visible: the control plane
seals a provider key under an algorithm string the enclave rejects, and that
customer's BYOK key stops working at the next inference request. Not degraded,
not slower — `unsupported envelope algorithm` from byokcache, on the prompt path,
for exactly the customers who took the trouble to bring their own keys.

WHY THIS EXISTS AS A GATE AND NOT AS A PARAGRAPH
------------------------------------------------
docs/design/byok-aad-v2-migration.md §4.0 states the ordering constraint and
then says the dangerous part out loud: the step-2 change reaches AWS and Azure
"as an ordinary version bump rather than as a deliberate migration step. Nobody
has to decide to run it." A rule whose enforcement is "somebody remembers §4.0
before deploying" is enforced by nothing.

It was in fact enforced by nothing. On AWS and Azure the control planes took the
v2-writing build with no check that their enclaves could read v2. That was
harmless — the migration record shows both audits found zero BYOK and zero
Broadcast secret rows, so there were no envelopes to break — but it was harmless
by accident of those databases being empty, not by any property of the deploy.
Each cloud is a standalone TrustedRouter with its own database
(docs/storage-portability/multi-cloud-separation.md), so the next cloud to grow
a BYOK row inherits the same unguarded sequence.

WHAT IT ACTUALLY CHECKS, per cloud and per serving region
---------------------------------------------------------
1. the running measurement, from a live attestation, is in the published
   accepted set;
2. every measurement in that accepted set was observed live by this run. An
   accepted measurement nobody served us is a build this run never checked, and
   the deploy is refused rather than described as covered;
3. the running measurement is the one the record maps to a commit, and that
   `source_commit` is present and is a git object id;
4. the formats the enclave built from that commit ACCEPTS, read from
   enclave-go/internal/byokcache/accepted_formats.json at that commit — a
   declaration GENERATED by a Go test that seals an envelope per format and
   requires (*Cache).Resolve to return the plaintext. The declaration pins a
   sha256 of every non-test .go file in that package and this script verifies
   each one against the same commit, so a declaration cannot describe a
   different package than the one that shipped;
5. the formats this working tree WRITES, derived from every construction of
   EncryptedSecretEnvelope anywhere under src/trusted_router — including
   through an alias, a subclass, or dataclasses.replace;
6. written ⊆ accepted.

Every step fails closed. A declaration it cannot read or cannot bind to the
source at that commit, a record it cannot map to a commit, a region it cannot
reach, an accepted measurement it never saw: all of those are failures, never
"assume the superset". Assuming the superset is the same as not running.

WHY A GENERATED DECLARATION AND NOT A PARSE OF cache.go
-------------------------------------------------------
The first version of this file answered "what does that build accept?" by
parsing the case labels out of the switch in `envelopeAAD`. A case label is not
acceptance. An adversarial review produced four compiling, gofmt-clean changes
that keep `case AlgorithmV2:` in the file and reject v2 anyway — an erroring
case body behind a feature flag, a kill-switch guard ahead of the switch, a
rejection in decryptEnvelope before envelopeAAD is ever called, and a renamed
live dispatch with the old function left as dead code — and all four passed the
gate with exit 0. That is the same mistake one level down from the one the old
docstring warned about: declaring `AlgorithmV2` is not accepting it, and neither
is naming it in a case label. So the answer now comes from a round trip through
the enclave's real entry point, recorded by the enclave repo's own test suite.

WHAT THIS DOES NOT ESTABLISH
----------------------------
* It does not verify any signature. The attestation is read for its measurement
  only, exactly as scripts/verify_trust_measurements.py reads it, and it shares
  that script's parsers so the two cannot drift. The cryptographically complete
  verifier is quill-cloud-proxy's tools/verify-attestation.py.
* It does not prove `source_commit` is the commit that built the running
  enclave. Neither PCR0 nor hostdata carries a commit; the field is an assertion
  by whoever ran the release. This check inherits that assertion's strength, and
  its whole value is that a WRONG assertion is now falsifiable (verify-pcr0.sh
  rebuilds PCR0 from a commit) where an ABSENT one was not.
* It does not prove the accepted-formats declaration was generated rather than
  written by hand. It proves the declaration matches the package source at the
  same commit, byte for byte. Someone who edits that package, recomputes the
  hashes by hand, and never runs CI defeats it; the pin is that
  quill-cloud-proxy's CI runs `go test ./...` on every push and pull request,
  and that test regenerates the declaration from behaviour and diffs it.
* The declaration covers the byokcache read path. A refusal further up the
  enclave — settlement.go declining to pass a v2 envelope to byokcache at all —
  is not visible to the probe and would read as accepted.
* It does not cover a bind window inside a single region. Two enclave builds
  behind one hostname answer one at a time, and the record names one commit for
  both. The check refuses in that case rather than guessing — see
  `_BIND_WINDOW` below — but "refuses" is not "verified both".
* It says nothing about envelopes already at rest. Reads are dispatched on the
  stored algorithm, so this is about what a deploy starts WRITING.
* Coverage is bounded by the record. Regions come from the record's `regions`
  array and the accepted set is cross-checked against what was observed, so a
  record that publishes more accepted measurements than this run saw is a
  refusal (step 2 — the control-plane mirror dropped the `regions` array until
  the fix in services/trust_release.py that ships beside this file, and against
  a plane predating that fix Azure now BLOCKS instead of quietly checking one
  region of two). What remains invisible is an enclave that serves this cloud
  while appearing in neither the `regions` array nor the accepted set: nothing
  in the record names it and no probe was ever routed to it.

Findings recorded while building this, both verified against the LIVE published
records rather than fixtures, and both fixed here:
  * the mirror read source_commit from the SERVING deployment's own settings
    instead of from the record it was mirroring, so trustedrouter.com reported
    `not-configured` for AWS and Azure no matter what quill-cloud-proxy
    published. Publishing the field upstream alone would have changed nothing.
  * the mirror dropped `regions`, making api-azure-sea.trustedrouter.com
    undiscoverable from the surface published as the place to verify us.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import re
import ssl
import sys
import urllib.error
import urllib.request
from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from scripts.verify_trust_measurements import (
    NOT_CONFIGURED,
    hostdata_from_maa_token,
    image_digest_from_confidential_space_token,
    pcr0_from_nitro_attestation,
)

REPO_ROOT = Path(__file__).resolve().parent.parent

# Every module that can persist an envelope, not the one that happens to today.
# The first version of this file read src/trusted_router/byok_crypto.py alone,
# so a write site in any other module was invisible and the gate passed.
WRITE_SURFACE = REPO_ROOT / "src" / "trusted_router"

DEFAULT_CONTROL_PLANE = "https://trustedrouter.com"
TIMEOUT_SECONDS = 25

# The enclave source of truth for what a build accepts. Read at a commit rather
# than from a checkout, because the question is what the RUNNING build accepts
# and that build is whatever commit the record names — not whatever
# quill-cloud-proxy's main happens to be today.
ENCLAVE_REPO = "Lore-Hex/quill-cloud-proxy"
ENCLAVE_PACKAGE = "enclave-go/internal/byokcache"
DECLARATION_PATH = f"{ENCLAVE_PACKAGE}/accepted_formats.json"
DECLARATION_SCHEMA = "trustedrouter/byok-accepted-formats/v1"

# The constructor whose `algorithm=` argument decides the format written. Every
# envelope this control plane persists is built here; grepping for the constant
# names instead would miss a new one, which is the failure mode that matters.
ENVELOPE_TYPE = "EncryptedSecretEnvelope"

# Calls that receive the envelope type as an ARGUMENT rather than calling it.
# Anything else that does so is building envelopes through an indirection this
# parser cannot follow (functools.partial, a registry, a factory table), so it
# fails closed instead.
_TYPE_USES = frozenset({"isinstance", "issubclass", "cast", "get_type_hints", "TypeVar"})

# Modules allowed to construct an envelope from a `**mapping`. Such a call
# REHYDRATES a row already in the database — its algorithm was chosen by
# whichever write site persisted it — so it cannot introduce a format, and
# there is no literal for this parser to read. The allowlist is deliberately a
# hardcoded refusal boundary rather than a rule: a `**mapping` construction in
# any other module blocks the deploy until a human decides which kind it is.
_REHYDRATION_MODULES = frozenset(
    {
        # ByokProviderConfig / BroadcastDestination.__post_init__, rebuilding a
        # stored dict into the dataclass.
        "src/trusted_router/storage_models.py",
        # The v1 -> v2 backfill, reading an envelope out of a row before
        # decrypting it. What it WRITES it writes through byok_crypto.
        "src/trusted_router/byok_aad_backfill.py",
    }
)

_COMMIT_RE = re.compile(r"^[0-9a-f]{7,40}$")

# (commit, repository-relative path) -> that file's bytes at that commit.
SourceReader = Callable[[str, str], bytes]

_BIND_WINDOW = (
    "a bind window publishes two measurements and one source_commit, so the "
    "outgoing build's accepted formats are unknown. Finish the enclave roll and "
    "narrow the accepted set before deploying the control plane -- that ordering "
    "is the whole of byok-aad-v2-migration.md section 4.0."
)


@dataclass(frozen=True)
class PlaneSpec:
    """How one cloud's release record names the thing the enclave measures."""

    cloud: str
    record_path: str
    accepted_key: str
    measurement_key: str
    measurement_label: str
    # AWS serves a certificate the enclave generated itself, so there is no
    # chain to validate. Same reasoning as verify_trust_measurements._fetch:
    # this is an unauthenticated read, adequate to learn what is running and
    # not adequate to authenticate the enclave.
    verify_tls: bool = True


PLANES: dict[str, PlaneSpec] = {
    "gcp": PlaneSpec(
        cloud="gcp",
        record_path="/trust/gcp-release.json",
        accepted_key="accepted_image_digests",
        measurement_key="image_digest",
        measurement_label="image digest",
    ),
    "aws": PlaneSpec(
        cloud="aws",
        record_path="/trust/aws-release.json",
        accepted_key="accepted_pcr0s",
        measurement_key="pcr0",
        measurement_label="PCR0",
        verify_tls=False,
    ),
    "azure": PlaneSpec(
        cloud="azure",
        record_path="/trust/azure-release.json",
        accepted_key="accepted_hostdata",
        measurement_key="hostdata",
        measurement_label="hostdata",
    ),
}


@dataclass(frozen=True)
class Region:
    """One serving endpoint, as the published record describes it.

    Enumerated from the record's `regions` array and never hardcoded: Azure
    serves from UAE North and Southeast Asia today, each running its own CCE
    policy and therefore its own hostdata, and a fourth region added tomorrow
    must be checked without editing this file.
    """

    host: str
    attestation_url: str
    measurement: str
    issuer: str | None
    source_commit: str | None


@dataclass
class RegionResult:
    cloud: str
    host: str
    measurement: str = ""
    source_commit: str = ""
    accepts: frozenset[str] = frozenset()
    problems: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.problems


# --------------------------------------------------------------------------
# What the control plane writes
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class WriteScan:
    """What the write-side scan found, including what it deliberately did not read."""

    formats: frozenset[str]
    # Constructions from a `**mapping`: an already-stored envelope being rebuilt.
    # Named rather than hidden, because they are the one construction shape this
    # scan reads no format out of.
    rehydration_sites: tuple[str, ...]


def read_write_surface(root: Path = WRITE_SURFACE) -> dict[str, str]:
    """Every Python module that could persist an envelope."""
    modules = {}
    for path in sorted(root.rglob("*.py")):
        modules[path.relative_to(REPO_ROOT).as_posix()] = path.read_text(encoding="utf-8")
    if not modules:
        raise ValueError(f"no Python modules under {root}; the write side is unreadable")
    return modules


def scan_write_surface(sources: Mapping[str, str]) -> WriteScan:
    """Envelope formats this build WRITES, derived from every module given.

    Deliberately not a hardcoded {"…-V2"}: hardcoding makes a gate correct
    exactly once, and the day a V3 write lands it would keep asserting the V2
    subset. Equally deliberately not "the `algorithm=` of every call spelled
    EncryptedSecretEnvelope in byok_crypto.py", which is what this was and which
    an adversarial review walked through five ways — a module-level alias of the
    constructor, a subclass, dataclasses.replace, assigning `.algorithm` after
    construction, and simply writing from another module. Each returned the
    old {V2} answer while the build wrote V3.

    So: every module under src/trusted_router is scanned; the set of names that
    reach the constructor is closed over aliases and subclasses first; a
    dataclasses.replace that sets algorithm= is a write; and an assignment to
    any `.algorithm` attribute anywhere is an outright refusal, because a format
    chosen after construction cannot be read off a constructor call.

    Fails closed on an `algorithm=` it cannot resolve to a module-level string
    constant. An expression there is not evidence of safety; it is a build whose
    written format is unknown, and unknown is the case the enclave breaks on.

    KNOWN BLIND SPOTS, named rather than implied:
      * a `**mapping` construction in a module on _REHYDRATION_MODULES. Those
        four calls rebuild an envelope already in the database, so they read a
        format rather than choosing one, and there is no literal here to read.
        The same shape in any other module blocks the deploy, and main() prints
        the sites it did not read.
      * an envelope constructed outside src/trusted_router entirely.
    An `algorithm=` computed at run time is NOT in that list: it raises. Being
    unable to read a format is a refusal, not an omission.
    """
    trees: dict[str, ast.Module] = {}
    for origin, source in sources.items():
        try:
            trees[origin] = ast.parse(source, filename=origin)
        except SyntaxError as exc:
            raise ValueError(f"cannot parse {origin}: {exc}") from exc

    constants = _module_level_string_constants(trees)

    written: set[str] = set()
    rehydration: list[str] = []
    unresolved: list[str] = []
    for origin, tree in trees.items():
        constructors = _constructor_names(tree)
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                _scan_call(node, origin, constructors, constants, written, rehydration, unresolved)
            elif _assigns_an_algorithm_attribute(node):
                unresolved.append(
                    f"{origin}:{node.lineno} assigns .algorithm after construction, so the "
                    "format written there cannot be read from the constructor call"
                )

    if unresolved:
        raise ValueError("cannot derive what this build writes: " + "; ".join(sorted(unresolved)))
    if not written:
        raise ValueError(
            f"found no {ENVELOPE_TYPE}(algorithm=...) under {WRITE_SURFACE}. Either the "
            "constructor moved or this parser has rotted; both mean the written format is unknown."
        )
    return WriteScan(formats=frozenset(written), rehydration_sites=tuple(sorted(rehydration)))


def written_formats(sources: Mapping[str, str]) -> frozenset[str]:
    """scan_write_surface's answer, for callers that need only the set."""
    return scan_write_surface(sources).formats


def _scan_call(
    node: ast.Call,
    origin: str,
    constructors: frozenset[str],
    constants: Mapping[str, set[str]],
    written: set[str],
    rehydration: list[str],
    unresolved: list[str],
) -> None:
    callee = _callee(node.func)
    where = f"{origin}:{node.lineno}"

    # The constructor handed to something else as a value: a factory, a
    # partial, a registry. Whatever that something does with it is out of
    # reach, so it is a refusal rather than a silent zero.
    if callee not in constructors and callee not in _TYPE_USES:
        for argument in [*node.args, *(keyword.value for keyword in node.keywords)]:
            if isinstance(argument, ast.Name) and argument.id in constructors:
                unresolved.append(
                    f"{where} passes {argument.id} to {callee or 'an expression'}(), so envelopes "
                    "may be built through an indirection this scan cannot follow"
                )
                return

    is_construction = callee in constructors
    is_replace = _is_dataclasses_replace(node)
    if not (is_construction or is_replace):
        return

    keywords = {keyword.arg for keyword in node.keywords}
    if is_construction and node.keywords and all(keyword.arg is None for keyword in node.keywords):
        # `EncryptedSecretEnvelope(**stored)`: rebuilding a row, not choosing a
        # format. Only where that is the established meaning; anywhere else the
        # same shape is a write whose format is unknown.
        # A plain reference only. `**{**stored, "algorithm": V3}` and
        # `**dict(stored, algorithm=V3)` are how a NEW format would arrive
        # through this shape, and both stay refusals.
        splat_only = len(node.keywords) == 1 and isinstance(
            node.keywords[0].value, ast.Name | ast.Attribute
        )
        if splat_only and not node.args and origin in _REHYDRATION_MODULES:
            rehydration.append(where)
            return
        unresolved.append(
            f"{where} builds an envelope from a mapping, so the format it writes is not in "
            "the source. If it rebuilds a stored envelope, add the module to "
            "_REHYDRATION_MODULES with the reason."
        )
        return
    if is_construction and (node.args or None in keywords):
        unresolved.append(f"{where} is not an all-keyword {ENVELOPE_TYPE}(...) call")
        return
    if "algorithm" not in keywords:
        # A replace() that does not touch algorithm keeps the stored one; a
        # construction with no algorithm= at all cannot be a valid envelope.
        if is_construction:
            unresolved.append(f"{where} constructs {ENVELOPE_TYPE} with no algorithm=")
        return

    values = [keyword.value for keyword in node.keywords if keyword.arg == "algorithm"]
    if len(values) != 1:
        unresolved.append(f"{where} passes algorithm= {len(values)} times")
        return
    resolved = _resolve_string(values[0], constants)
    if resolved is None:
        unresolved.append(f"{where}: algorithm= is not a module-level string constant")
        return
    written.add(resolved)


def _module_level_string_constants(trees: Mapping[str, ast.Module]) -> dict[str, set[str]]:
    """Module-level `NAME = "…"` across the whole surface, keyed by name.

    Keyed by name rather than by module so `algorithm=ALGORITHM_V2` resolves in
    a module that imported it. A name defined twice with different values maps
    to two values and therefore resolves to neither: ambiguous is unknown, and
    unknown blocks.
    """
    constants: dict[str, set[str]] = {}
    for tree in trees.values():
        for node in tree.body:
            if not isinstance(node, ast.Assign) or not isinstance(node.value, ast.Constant):
                continue
            if not isinstance(node.value.value, str):
                continue
            for target in node.targets:
                if isinstance(target, ast.Name):
                    constants.setdefault(target.id, set()).add(node.value.value)
    return constants


def _constructor_names(tree: ast.Module) -> frozenset[str]:
    """Every name in this module that reaches the envelope constructor.

    `E = EncryptedSecretEnvelope` at any scope, `from … import X as E`, and
    `class E(EncryptedSecretEnvelope)` all produce a callable that writes an
    envelope. Closed over repeatedly so an alias of an alias is included.
    """
    names = {ENVELOPE_TYPE}
    for _ in range(8):
        before = set(names)
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom):
                for alias in node.names:
                    if alias.name == ENVELOPE_TYPE and alias.asname:
                        names.add(alias.asname)
            elif isinstance(node, ast.Assign) and isinstance(node.value, ast.Name):
                if node.value.id in names:
                    names.update(
                        target.id for target in node.targets if isinstance(target, ast.Name)
                    )
            elif isinstance(node, ast.ClassDef):
                if any(_callee(base) in names for base in node.bases):
                    names.add(node.name)
        if names == before:
            break
    return frozenset(names)


def _is_dataclasses_replace(node: ast.Call) -> bool:
    """`dataclasses.replace(envelope, algorithm=…)` writes a format too."""
    if isinstance(node.func, ast.Attribute) and node.func.attr == "replace":
        return isinstance(node.func.value, ast.Name) and node.func.value.id == "dataclasses"
    return isinstance(node.func, ast.Name) and node.func.id == "replace"


def _assigns_an_algorithm_attribute(node: ast.AST) -> bool:
    targets: Iterable[ast.expr]
    if isinstance(node, ast.Assign):
        targets = node.targets
    elif isinstance(node, ast.AugAssign | ast.AnnAssign):
        targets = [node.target]
    else:
        return False
    return any(isinstance(t, ast.Attribute) and t.attr == "algorithm" for t in targets)


def _resolve_string(value: ast.expr, constants: Mapping[str, set[str]]) -> str | None:
    if isinstance(value, ast.Constant) and isinstance(value.value, str):
        return value.value
    name = value.id if isinstance(value, ast.Name) else None
    if isinstance(value, ast.Attribute):
        name = value.attr
    if name is not None and len(constants.get(name, set())) == 1:
        return next(iter(constants[name]))
    return None


def _callee(func: ast.expr) -> str:
    if isinstance(func, ast.Name):
        return func.id
    if isinstance(func, ast.Attribute):
        return func.attr
    return ""


# --------------------------------------------------------------------------
# What the enclave accepts
# --------------------------------------------------------------------------

_GO_FILENAME = re.compile(r"^[A-Za-z0-9_.-]+\.go$")
_SHA256_HEX = re.compile(r"^[0-9a-f]{64}$")


def accepted_formats(commit: str, read: SourceReader) -> frozenset[str]:
    """Envelope formats the enclave built from `commit` ACCEPTS.

    Read from the generated declaration at
    enclave-go/internal/byokcache/accepted_formats.json, NOT parsed out of
    cache.go. The declaration is written by a Go test that, for every algorithm
    constant the package declares, seals an envelope with the control plane's
    own associated data and requires (*Cache).Resolve — the entry point on the
    prompt path — to return the plaintext. A format is in `accepted` because a
    round trip succeeded, not because a case label exists.

    That distinction is the whole reason this function changed shape. Reading
    the switch, four compiling and gofmt-clean edits kept `case AlgorithmV2:`
    while rejecting v2: an erroring case body, a kill switch ahead of the
    switch, a rejection in the caller, and a renamed live dispatch with the old
    function left behind as dead code. All four passed. All four fail a round
    trip.

    The declaration is bound to the source by `source_sha256`, which names every
    non-test .go file in that package. Each is fetched at the SAME commit and
    hashed here, so a declaration that predates a change to the package is
    refused rather than believed: whoever changed the package has to re-run the
    test, which re-runs the probe.

    Fails closed on: no declaration at that commit (a build older than this
    mechanism cannot be checked this way and must not be assumed to accept
    anything), an unreadable or wrong-schema declaration, a hash that does not
    match, or a probe that declared its own control value accepted.
    """
    origin = f"{DECLARATION_PATH}@{commit}"
    try:
        declaration = json.loads(read(commit, DECLARATION_PATH))
    except json.JSONDecodeError as exc:
        raise ValueError(f"{origin} is not JSON: {exc}") from exc
    if not isinstance(declaration, dict):
        raise ValueError(f"{origin} is a {type(declaration).__name__}, not a declaration")
    if declaration.get("schema") != DECLARATION_SCHEMA:
        raise ValueError(
            f"{origin} declares schema {declaration.get('schema')!r}, expected "
            f"{DECLARATION_SCHEMA!r}. A schema this script does not know is a declaration it "
            "cannot read, not one it may skip."
        )
    if declaration.get("package") != ENCLAVE_PACKAGE:
        raise ValueError(
            f"{origin} describes package {declaration.get('package')!r}, not {ENCLAVE_PACKAGE!r}"
        )

    accepted = declaration.get("accepted")
    if not isinstance(accepted, list) or not accepted:
        raise ValueError(f"{origin} declares no accepted formats")
    if any(not isinstance(value, str) or not value for value in accepted):
        raise ValueError(f"{origin}: `accepted` must be non-empty strings")

    control = declaration.get("rejected_control")
    if not isinstance(control, str) or not control:
        raise ValueError(
            f"{origin} names no rejected_control. Without a format the probe confirmed it "
            "REJECTS, `accepted` could have been produced by a probe that accepts everything."
        )
    if control in accepted:
        raise ValueError(
            f"{origin} lists its own control value {control!r} as accepted, so the probe that "
            "produced it cannot distinguish acceptance from rejection."
        )

    _verify_declaration_binds_to_source(commit, read, declaration, origin)
    return frozenset(accepted)


def _verify_declaration_binds_to_source(
    commit: str, read: SourceReader, declaration: dict[str, Any], origin: str
) -> None:
    """Every file the declaration pins must hash to what the declaration says.

    This is what stops a stale declaration from describing a package that has
    since changed. It does NOT prove the declaration was generated rather than
    hand-written; that is quill-cloud-proxy CI running the generating test on
    every push, and it is stated as a limit in this module's docstring.
    """
    hashes = declaration.get("source_sha256")
    if not isinstance(hashes, dict) or not hashes:
        raise ValueError(f"{origin} pins no source files, so it is bound to no particular build")
    for name, digest in sorted(hashes.items()):
        if not isinstance(name, str) or not _GO_FILENAME.fullmatch(name):
            raise ValueError(f"{origin} pins {name!r}, which is not a .go file in that package")
        if not isinstance(digest, str) or not _SHA256_HEX.fullmatch(digest):
            raise ValueError(f"{origin} pins {name} to {digest!r}, which is not a sha256")
        body = read(commit, f"{ENCLAVE_PACKAGE}/{name}")
        actual = hashlib.sha256(body).hexdigest()
        if actual != digest:
            raise ValueError(
                f"{origin} pins {name} to {digest[:12]}… but {name} at {commit} hashes to "
                f"{actual[:12]}…. The declaration describes a different build than this commit's "
                "source, so what that enclave accepts was never measured. Re-run the generator in "
                "quill-cloud-proxy and publish a commit whose declaration matches its package."
            )


# --------------------------------------------------------------------------
# Fetching
# --------------------------------------------------------------------------


def _fetch(url: str, *, verify_tls: bool = True, headers: dict[str, str] | None = None) -> bytes:
    context: ssl.SSLContext | None = None
    if not verify_tls:
        context = ssl.create_default_context()
        context.check_hostname = False
        context.verify_mode = ssl.CERT_NONE
    if not url.startswith("https://"):
        # Scheme is fixed by construction; assert it anyway so a record served
        # to us cannot turn this into a file:// read.
        raise ValueError(f"refusing to fetch non-HTTPS URL {url!r}")
    request = urllib.request.Request(url, headers={"accept": "*/*", **(headers or {})})  # noqa: S310
    with urllib.request.urlopen(  # noqa: S310 - scheme checked above
        request, timeout=TIMEOUT_SECONDS, context=context
    ) as response:
        return bytes(response.read())


def fetch_record(control_plane: str, path: str) -> dict[str, Any]:
    """Published release record. Absence is a failure, not a skip.

    scripts/verify_trust_measurements.py treats an unpublished record as SKIP,
    which is right for a drift report: it is answering "does what we publish
    match what runs", and there is nothing to compare. This is a deploy gate
    answering "may this build write v2 here", and no record means no evidence.
    """
    url = f"{control_plane.rstrip('/')}{path}"
    try:
        body = _fetch(url)
    except urllib.error.HTTPError as exc:  # noqa: UP041 - urllib error hierarchy
        raise ValueError(f"{url} returned HTTP {exc.code}; no published record to check") from exc
    record = json.loads(body)
    if not isinstance(record, dict):
        raise ValueError(f"{url} returned a {type(record).__name__}, not a release record")
    return record


def fetch_enclave_file(commit: str, path: str) -> bytes:
    """One file from the enclave repository as it was at `commit`.

    Bytes, not text: what comes back is hashed against the declaration's pin,
    and a decode-then-encode round trip is not the identity on every input.

    GH_TOKEN is used when present only to raise the anonymous rate limit; the
    repository is public and nothing here needs authority.
    """
    if not _COMMIT_RE.fullmatch(commit):
        raise ValueError(f"{commit!r} is not a git object id")
    url = f"https://raw.githubusercontent.com/{ENCLAVE_REPO}/{commit}/{path}"
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    headers = {"authorization": f"Bearer {token}"} if token else None
    try:
        return _fetch(url, headers=headers)
    except urllib.error.HTTPError as exc:  # noqa: UP041 - urllib error hierarchy
        hint = ""
        if path == DECLARATION_PATH and exc.code == 404:
            hint = (
                " That build predates the generated declaration, so what it accepts was never "
                "measured. Roll an enclave built from a commit that carries "
                f"{DECLARATION_PATH} before deploying a control plane against it."
            )
        raise ValueError(
            f"cannot read {path} at {commit} (HTTP {exc.code}). Without it the formats that "
            f"enclave accepts are unknown, and unknown fails closed.{hint}"
        ) from exc


def _attestation_url(record: dict[str, Any]) -> str:
    """Attestation endpoint for a record with no per-region array.

    Derived from api_base_url rather than listed here, so a plane that moves
    hostnames does not need this file edited to keep being checked.
    """
    base = record.get("api_base_url")
    if not isinstance(base, str) or not base.startswith("https://"):
        raise ValueError("record has no https api_base_url to derive an attestation URL from")
    parts = urlsplit(base)
    return f"{parts.scheme}://{parts.netloc}/attestation"


def regions_of(record: dict[str, Any], spec: PlaneSpec) -> list[Region]:
    """Every serving region the record describes.

    From the record's `regions` array when it has one. Azure does, because its
    regions genuinely differ — each runs its own CCE policy, so hostdata is a
    real set rather than a bind-window artifact. GCP and AWS publish a single
    plane and no array, which is one region, not zero.
    """
    entries = record.get("regions")
    record_commit = record.get("source_commit")
    if isinstance(entries, list) and entries:
        regions: list[Region] = []
        for index, entry in enumerate(entries):
            if not isinstance(entry, dict):
                raise ValueError(f"regions[{index}] is not an object")
            url = entry.get("attestation_url")
            measurement = entry.get(spec.measurement_key)
            if not isinstance(url, str) or not isinstance(measurement, str):
                raise ValueError(
                    f"regions[{index}] is missing attestation_url or {spec.measurement_key}"
                )
            issuer = entry.get("attestation_issuer")
            regions.append(
                Region(
                    host=urlsplit(url).netloc or url,
                    attestation_url=url,
                    measurement=measurement,
                    issuer=issuer if isinstance(issuer, str) else None,
                    # A per-region source_commit when the producer can attribute
                    # one; the record-wide value otherwise. capture-plane-
                    # measurements.py writes only the latter today.
                    source_commit=entry.get("source_commit") or record_commit,
                )
            )
        return regions

    measurement = record.get(spec.measurement_key)
    if not isinstance(measurement, str):
        raise ValueError(f"record has no {spec.measurement_key}")
    url = _attestation_url(record)
    return [
        Region(
            host=urlsplit(url).netloc,
            attestation_url=url,
            measurement=measurement,
            issuer=record.get("attestation_issuer"),
            source_commit=record_commit,
        )
    ]


def live_measurement(spec: PlaneSpec, payload: bytes) -> tuple[str, str | None]:
    """(measurement, issuer) from one region's live attestation.

    The parsers are imported from scripts/verify_trust_measurements.py rather
    than rewritten. Two fail-closed COSE parsers is one fail-closed COSE parser
    and one that quietly stopped being fail-closed.
    """
    if spec.cloud == "aws":
        return pcr0_from_nitro_attestation(payload), None
    if spec.cloud == "azure":
        hostdata, issuer = hostdata_from_maa_token(payload)
        return hostdata, issuer
    return image_digest_from_confidential_space_token(payload), None


# --------------------------------------------------------------------------
# The check
# --------------------------------------------------------------------------

Attestor = Callable[[str, bool], bytes]


def check_plane(
    spec: PlaneSpec,
    record: dict[str, Any],
    written: frozenset[str],
    *,
    attest: Attestor,
    source: SourceReader,
    source_cache: dict[str, frozenset[str]] | None = None,
) -> list[RegionResult]:
    """One cloud, every region it publishes."""
    cache = source_cache if source_cache is not None else {}
    accepted_set = [
        value
        for value in record.get(spec.accepted_key) or []
        if isinstance(value, str) and value != NOT_CONFIGURED
    ]
    issuers = [value for value in record.get("attestation_issuers") or [] if isinstance(value, str)]

    results: list[RegionResult] = []
    observed: set[str] = set()
    for region in regions_of(record, spec):
        result = RegionResult(cloud=spec.cloud, host=region.host)
        results.append(result)

        if not accepted_set:
            result.problems.append(f"record publishes no {spec.accepted_key}")
            continue

        try:
            running, issuer = live_measurement(
                spec, attest(region.attestation_url, spec.verify_tls)
            )
        except Exception as exc:  # noqa: BLE001 - any failure to read is a failure to clear
            result.problems.append(f"cannot read a live attestation: {exc}")
            continue
        result.measurement = running
        observed.add(running)

        if running not in accepted_set:
            result.problems.append(
                f"running {spec.measurement_label} is not in the published accepted set "
                f"({', '.join(accepted_set)})"
            )
            continue

        # An accepted measurement that is not the one this record maps to a
        # commit. Which build is running is then unknown, so what it accepts is
        # unknown too.
        if running != region.measurement:
            result.problems.append(
                f"running {spec.measurement_label} {running} is accepted but the record maps "
                f"{region.measurement} to source_commit; {_BIND_WINDOW}"
            )
            continue

        # A region we are being served by that the record does not describe.
        # Which region answers a shared name is Traffic Manager's decision, not
        # ours, so this is how a live region absent from the record shows up.
        if issuer is not None:
            if region.issuer is not None and issuer != region.issuer:
                result.problems.append(
                    f"attestation came from {issuer}, but the record says this endpoint is "
                    f"{region.issuer} — a region is serving that this record does not describe"
                )
                continue
            if issuers and issuer not in issuers:
                result.problems.append(
                    f"live attestation issuer {issuer} is in no published issuer list "
                    "— a region is serving that this record does not describe"
                )
                continue

        commit = region.source_commit
        if not isinstance(commit, str) or not commit or commit == NOT_CONFIGURED:
            result.problems.append(
                "record carries no source_commit, so the running build cannot be mapped to "
                "source and its accepted formats are unknowable. In quill-cloud-proxy run "
                "`python3 tools/capture-plane-measurements.py --write --source-commit <sha "
                "that built the RUNNING enclave>` and commit trust-page/. That flag has no "
                "default: HEAD is the released build only by coincidence."
            )
            continue
        if not _COMMIT_RE.fullmatch(commit):
            result.problems.append(f"source_commit {commit!r} is not a git object id")
            continue
        result.source_commit = commit

        if commit not in cache:
            try:
                cache[commit] = accepted_formats(commit, source)
            except Exception as exc:  # noqa: BLE001 - unread is unknown is failed
                result.problems.append(str(exc))
                continue
        result.accepts = cache[commit]

        missing = sorted(written - result.accepts)
        if missing:
            result.problems.append(
                f"this build WRITES {', '.join(sorted(written))} but the enclave at {commit} "
                f"ACCEPTS only {', '.join(sorted(result.accepts))}. Deploying it breaks every "
                f"BYOK key in the {spec.cloud} database at the next inference request. "
                f"Unreadable: {', '.join(missing)}."
            )

    # The record holds both numbers and the first version of this file never
    # compared them: it probed one Azure enclave, and printed a sentence about
    # every enclave serving Azure. An accepted measurement that no region
    # served us belongs to a build this run did not check, and a claim about
    # every serving enclave cannot be made over a subset of them.
    unchecked = sorted(value for value in accepted_set if value not in observed)
    if unchecked:
        results.append(
            RegionResult(
                cloud=spec.cloud,
                host="-",
                problems=[
                    f"the record accepts {len(accepted_set)} {spec.measurement_label} value(s) and "
                    f"this run observed {len(observed)} across the {len(results)} region(s) the "
                    f"record describes. Never served to us, therefore never checked: "
                    f"{', '.join(unchecked)}. Either a region is missing from the record's "
                    "`regions` array, or the accepted set still names a build that is no longer "
                    "serving -- narrow it, or publish the region, then re-run."
                ],
            )
        )
    return results


def gather(
    control_plane: str,
    clouds: Sequence[str],
    written: frozenset[str],
    *,
    records: Callable[[str], dict[str, Any]],
    attest: Attestor,
    source: SourceReader,
) -> list[RegionResult]:
    cache: dict[str, frozenset[str]] = {}
    results: list[RegionResult] = []
    for cloud in clouds:
        spec = PLANES[cloud]
        try:
            record = records(spec.record_path)
        except Exception as exc:  # noqa: BLE001
            results.append(
                RegionResult(cloud=cloud, host="-", problems=[f"no usable release record: {exc}"])
            )
            continue
        try:
            results.extend(
                check_plane(spec, record, written, attest=attest, source=source, source_cache=cache)
            )
        except Exception as exc:  # noqa: BLE001
            results.append(
                RegionResult(cloud=cloud, host="-", problems=[f"record is unreadable: {exc}"])
            )
    return results


# --------------------------------------------------------------------------
# Output
# --------------------------------------------------------------------------

_SHORT = re.compile(r"^TR-BYOK-ENVELOPE-AES-256-GCM-(V\d+)$")


def _short(algorithm: str) -> str:
    match = _SHORT.match(algorithm)
    return match.group(1) if match else algorithm


def _shorts(algorithms: frozenset[str]) -> str:
    return ",".join(_short(value) for value in sorted(algorithms)) or "-"


def _elide(measurement: str) -> str:
    if not measurement:
        return "-"
    return measurement[:19] + "…" if len(measurement) > 20 else measurement


def render(results: Sequence[RegionResult], written: frozenset[str]) -> str:
    rows = [("CLOUD", "REGION", "MEASUREMENT", "COMMIT", "ACCEPTS", "WRITES", "")]
    for result in results:
        rows.append(
            (
                result.cloud,
                result.host,
                # "-" means NOT READ. A short measurement is still a measurement:
                # printing it as "-" would make a row that was checked look
                # identical to one that was not, in the table an operator reads
                # at the moment a deploy stops.
                _elide(result.measurement),
                result.source_commit or "-",
                _shorts(result.accepts),
                _shorts(written),
                "ok" if result.ok else "BLOCKED",
            )
        )
    widths = [max(len(row[i]) for row in rows) for i in range(len(rows[0]))]
    lines = [
        "  ".join(cell.ljust(widths[i]) for i, cell in enumerate(row)).rstrip() for row in rows
    ]
    for result in results:
        for problem in result.problems:
            lines.append(f"\nBLOCKED {result.cloud}/{result.host}: {problem}")
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--control-plane", default=DEFAULT_CONTROL_PLANE)
    parser.add_argument(
        "--cloud",
        action="append",
        choices=sorted(PLANES),
        help=(
            "cloud to gate on; repeatable. Default: all of them. A deploy should pass its OWN "
            "cloud -- the databases are separate, so Azure's enclave has no say over a GCP "
            "rollout and blocking one on the other only teaches people to bypass the gate."
        ),
    )
    args = parser.parse_args(argv)
    clouds = args.cloud or sorted(PLANES)

    try:
        scan = scan_write_surface(read_write_surface())
    except (OSError, ValueError) as exc:
        print(f"cannot determine what this build writes: {exc}", file=sys.stderr)
        return 1
    written = scan.formats

    results = gather(
        args.control_plane,
        clouds,
        written,
        records=lambda path: fetch_record(args.control_plane, path),
        attest=lambda url, verify_tls: _fetch(url, verify_tls=verify_tls),
        source=fetch_enclave_file,
    )

    print(render(results, written))
    blocked = [result for result in results if not result.ok]
    if blocked:
        print(
            f"\n{len(blocked)} serving region(s) block this deploy. The control plane may only "
            "write envelope formats every enclave serving its cloud already reads; see "
            "docs/design/byok-aad-v2-migration.md section 4.0.",
            file=sys.stderr,
        )
        return 1
    # Says what was checked, not what is true of the world. Every measurement
    # each record accepts was observed live (check_plane refuses otherwise) and
    # every one mapped to a commit whose generated declaration covers what this
    # build writes. An enclave serving this cloud that appears in neither the
    # record's regions nor its accepted set is outside what any of this saw.
    print(
        f"\n{len(results)} serving region(s) checked for {', '.join(clouds)}; every measurement "
        f"those records accept was observed live, and each of those enclaves declares it accepts "
        f"every format this build writes ({_shorts(written)})."
    )
    if scan.rehydration_sites:
        print(
            "Not read as writes (an envelope rebuilt from a stored mapping): "
            + ", ".join(scan.rehydration_sites)
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
