"""NYTE Token Index: the public quotes and grade cards for /index.

Generated by nytokenexchange scripts/render_public_page.py; regenerate there, do not edit by hand.
The page publishes fixed chart images and these quotes only (no series data).
"""

AS_OF = "September 29, 2026"
AS_OF_ISO = "2026-09-29"
QUOTES: dict[str, dict[str, object]] = {
    "ALL": {
        "label": "NYTE Token Index",
        "value": 375,
        "change_7d": -6.1
    },
    "AAA": {
        "label": "AAA Frontier",
        "value": 2982,
        "change_7d": -24.5
    },
    "A": {
        "label": "A Advanced",
        "value": 1121,
        "change_7d": -12.9
    },
    "B": {
        "label": "B Professional",
        "value": 204,
        "change_7d": -4.1
    },
    "C": {
        "label": "C Efficient",
        "value": 40,
        "change_7d": 0.0
    }
}
GRADES: list[dict[str, object]] = [
    {
        "code": "AAA",
        "name": "Frontier",
        "use": "Frontier research, the hardest reasoning, strategic synthesis. The leading labs' current flagships.",
        "examples": [
            "Claude Opus 5.5",
            "GPT-6 Astra",
            "Claude Fable 5.1"
        ]
    },
    {
        "code": "A",
        "name": "Advanced",
        "use": "Coding agents, complex analysis, professional workflows that need near-frontier capability.",
        "examples": [
            "Kimi K3",
            "Claude Opus 5",
            "GLM-5.3",
            "GPT-6 Sol",
            "Claude Fable 5"
        ]
    },
    {
        "code": "B",
        "name": "Professional",
        "use": "Production assistants, structured analysis, code review, document work at scale.",
        "examples": [
            "DeepSeek V4.1 Flash",
            "GLM-5.3 Flash",
            "DeepSeek V4 Pro",
            "GLM-5.2",
            "Gemini 3.8 Flash"
        ]
    },
    {
        "code": "C",
        "name": "Efficient",
        "use": "Extraction, summarization, classification, routing, high-volume support.",
        "examples": [
            "DeepSeek V4 Flash",
            "Gemini 2.5 Flash-Lite",
            "GPT-5 mini",
            "GPT-4.1 mini"
        ]
    }
]
CHART_ALT: dict[str, str] = {
    "nyte": "Line chart of the NYTE Token Index in US dollars per billion tokens from May to September 2026, peaking near $1,238 in June and ending near $375.",
    "grades": "Log-scale chart of the four NYTE grade indices in US dollars per billion tokens from May to September 2026, ending with Frontier near $2,982, Advanced near $1,121, Professional near $204, Efficient near $40."
}


def token_index_context() -> dict[str, object]:
    return {"as_of": AS_OF, "as_of_iso": AS_OF_ISO, "quotes": QUOTES, "grades": GRADES, "chart_alt": CHART_ALT}
